### PR TITLE
Get started

### LINKED ISSUE #896: Update and enhance how-to-guide section
This issue is to track :
* What has been done and 
* What we are on currently working :)

## Team members
Abhishek Jaiswal - @abhishek-iiit 
Vasvi Sood  - @vasvi-sood 

# References 
- [x] **Readme(to github section)** 
- [x] **Overview** 
- [x] **Add events to the bot**
    - [x] Add events and customise a bot
- [x] **Add more functionality to your bot**
    - [x] Dealing with messages
    - [x] Manage Contacts
    - [x] Manage Rooms
    - [x] Send and Accept Friend Requests
    - [x] Sending and Receiving files
- [x] **Deploy on IM platfrom**
    - [x] Deploy in Wechat
    - [x] Deploy in Whatsapp
    - [x] Deploy in Lark
    - [x] Deploy in Gitter
    - [x] Deploy in Wechat Official Account
    - [x] Deploy in PadLocal
    - [x] Deploy in WeChat4U
- [x] **Overview with containers**
    - [x] Deploy with Heroku
    - [x] Deploy with Docker

Please link pull request to this section for the easy access.

### PR DESCRIPTION
**Pull request by abhishek-iiit**
## Get Started 
Screenshot from 2021-06-17 01-13-16
Screenshot from 2021-06-17 01-13-29

### CODE REVIEW

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Very good, you have started to get comfortable with git, excellent PR.

**Comment by proudofsimin** [comment]
Hi @abhishek-iiit and @vasvi-sood,

I guess this is the reopen of #906. Like I mentioned in the last PR and in the first meeting. We don't need to document about the installation in how-to guides as it's within tutorials' scope (#905).

**Comment by Rohitesh-Kumar-Jain** [comment]
@vasvi-sood  We would be glad if you may once go through the PR, and either request for changes or approve the PR.

**Review by vasvi-sood — APPROVED** [review]
LGTM

**Comment by Rohitesh-Kumar-Jain** [comment]
@proudofsimin so what is to be done, finally?

**Comment by abhishek-iiit** [comment]
@proudofsimin As discussed in the biweekly meeting, can we remove this section from How to guide ?

**Comment by proudofsimin** [comment]
> @proudofsimin As discussed in the biweekly meeting, can we remove this section from How to guide ?

yes, please. Thank you.

**Comment by abhishek-iiit** [comment]
Closing this PR as discussed in meeting for How to guide section

**Pull request closed without merging**
