### PR TITLE
[Week3] Add events to the bot

### PR DESCRIPTION
**Pull request by abhishek-iiit**
## Add Events to the Bot : Getting Started
Screenshot from 2021-06-06 12-14-13
Screenshot from 2021-06-06 12-14-26

## Add Events to the Bot : Adding Events and Customising a bot
Screenshot from 2021-06-06 12-14-38
Screenshot from 2021-06-06 12-14-52
Screenshot from 2021-06-06 12-15-08
Screenshot from 2021-06-06 12-15-17
Screenshot from 2021-06-06 12-15-24
Screenshot from 2021-06-06 12-19-03
Screenshot from 2021-06-06 12-19-10
Screenshot from 2021-06-06 12-19-20
Screenshot from 2021-06-06 12-19-30
Screenshot from 2021-06-06 12-19-37
Screenshot from 2021-06-06 12-19-47

### CODE REVIEW

**Review by Rohitesh-Kumar-Jain — CHANGES_REQUESTED** [review]
Hey, you have made a common mistake of switching from one feature branch to the other feature branch directly. If we merge #901 we are going to have merge conflicts with this PR. This is not how you are supposed to work on multiple features 😅

**Comment by Rohitesh-Kumar-Jain** [comment]
This is how I work on more than two features...

1) git switch master
2) git switch -c feature1

work on feature 1, commit your changes.

3) git switch master
4) git switch -c feature 2

work on feature 2, commit your changes.


Pls check on which branch you are currently working before committing or raising PRs.

PRs like this one aren't acceptable. Pls refactor this PR or close this to raise a new one, so that we can start reviewing the documenatation.

**Comment by abhishek-iiit** [comment]
> This is how I work on more than two features...
> 
>     1. git switch master
> 
>     2. git switch -c feature1
> 
> 
> work on feature 1, commit your changes.
> 
>     1. git switch master
> 
>     2. git switch -c feature 2
> 
> 
> work on feature 2, commit your changes.
> 
> Pls check on which branch you are currently working before committing or raising PRs.
> 
> PRs like this one isn't acceptable. Pls refactor this PR or close this to raise a new one, so that we can start reviewing the documentation.

Sorry for this mistake of switching the branch directly.
Will correct the PR by tonight as soon as possible.
Thankyou mentor

**Comment by abhishek-iiit** [comment]
Closing this PR. Please #948 & #958

**Pull request closed without merging**
