### PR TITLE
Update profile info in landing page

### PR DESCRIPTION
**Pull request by hailiang-wang**
Related with https://github.com/wechaty/wechaty.js.org/issues/1394

### CODE REVIEW

**Review by huan — APPROVED** [review]
LGTM

**Review by sajen-k — APPROVED** [review]
LGTM

**Comment by chuangfengwang** [comment]
LGTM

**Review by chuangfengwang — APPROVED** [review]
LGTM

**Comment by hailiang-wang** [comment]
@nibble0101 Could you help review this PR, thanks.

**Pull request merged**
