### PR TITLE
new blog for 企业微信puppet

### PR DESCRIPTION
**Pull request by YQXie99**
new blog for 企业微信puppet

### CODE REVIEW

**Comment by lijiarui** [comment]
Please make ci green then I can review your blog!

Thanks!

**Comment by lijiarui** [comment]
@Sapio-S  I will close this PR if this PR has no reply at the end of September.

**Comment by lijiarui** [comment]
@wj-Mcat  Please help @Sapio-S  posting his blog.

**Comment by wj-Mcat** [comment]
This blog is way past the deadline, If you have not complete this issue in next week, we will close this issue. Thanks for your attention.

**Pull request closed without merging**
