### PR TITLE
GSOD'21 Proposal shwetal soni

### PR DESCRIPTION
**Pull request by shwetalsoni**

### CODE REVIEW

**Review by huan — CHANGES_REQUESTED** [review]
Thank you very much for adding your introduction blog post as a GSoD'21 technical writer!

Please make sure the CI turns green by fixing all the issues showed by the GitHub Actions so that we can continue reviewing this PR.

**Comment by shwetalsoni** [comment]
> Thank you very much for adding your introduction blog post as a GSoD'21 technical writer!
> 
> Please make sure the CI turns green by fixing all the issues showed by the GitHub Actions so that we can continue reviewing this PR.

@huan Can you please tell me what can I do to make it alright. I m not getting why is it failing or how do I check it.

**Comment by huan** [comment]
Link to #817

**Comment by huan** [comment]
> not ok 38 "jekyll/_posts/2021-03-05-gsod-project-proposal-shwetal-wechaty.md" has category "project": it's tags should contain one of "automotive,devops,ecommerce,ecosystem,education,entertainment,finance,game,healthcare,hospitality,insurance,media,other,productivity,real-estate,social,travel,utility" Learn more from Issue #710: Enforce blog posts with category "project" to contain one of the tags Url: https://github.com/wechaty/wechaty.js.org/issues/710

I believe you have fixed a series of issues that showed in GitHub Action.

The above error message means that: when you are using a `category` name with `project`, then the `tag` should contain the following names at least:

```ts
const TAGS = {
    education     : 'Mobile learning, talk to the professor, application management, and manage course schedules',
    entertainment : 'Movie updates, booking tickets, etc.',
    estate        : 'Sales, schedule appointments, customer support, etc',
    finance       : 'banking and Insurance: Account updates, OTPs, account transactions, Suspicious account, Insurance premium updates, and payment, recommend right insurance products, compare insurance premiums, password setting, and new loans, credit card updates, etc.',
    media         : 'Send digital newspapers, etc.',
    retail        : 'E-commerce expansion on SMS messaging platform; browsing, promotions, and complete transactions.',
    telecom       : 'Send Bills, complete payment, customer support, new connection/product, etc.',
    travel        : 'Browse hotels and tickets, booking, send boarding pass, etc',
  }
```

I'd like to suggest that you should change the `category` from `project` to `article` which is more meaningful for this post.

**Comment by shwetalsoni** [comment]
> > not ok 38 "jekyll/_posts/2021-03-05-gsod-project-proposal-shwetal-wechaty.md" has category "project": it's tags should contain one of "automotive,devops,ecommerce,ecosystem,education,entertainment,finance,game,healthcare,hospitality,insurance,media,other,productivity,real-estate,social,travel,utility" Learn more from Issue #710: Enforce blog posts with category "project" to contain one of the tags Url: #710
> 
> I believe you have fixed a series of issues that showed in GitHub Action.
> 
> The above error message means that: when you are using a `category` name with `project`, then the `tag` should contain the following names at least:
> 
> ```ts
> const TAGS = {
>     education     : 'Mobile learning, talk to the professor, application management, and manage course schedules',
>     entertainment : 'Movie updates, booking tickets, etc.',
>     estate        : 'Sales, schedule appointments, customer support, etc',
>     finance       : 'banking and Insurance: Account updates, OTPs, account transactions, Suspicious account, Insurance premium updates, and payment, recommend right insurance products, compare insurance premiums, password setting, and new loans, credit card updates, etc.',
>     media         : 'Send digital newspapers, etc.',
>     retail        : 'E-commerce expansion on SMS messaging platform; browsing, promotions, and complete transactions.',
>     telecom       : 'Send Bills, complete payment, customer support, new connection/product, etc.',
>     travel        : 'Browse hotels and tickets, booking, send boarding pass, etc',
>   }
> ```
> 
> I'd like to suggest that you should change the `category` from `project` to `article` which is more meaningful for this post.

Thanks @huan for guiding me. After so many attempts I did it successfully.

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for adding your intro blog post to the community, welcome on boarding!

**Pull request merged**
