### PR TITLE
Update vorpal with wechaty doc

### PR DESCRIPTION
**Pull request by sbis04**
I have added a **Requirements** sections to the doc of **Using Vorpal with Wechaty**, and fixed the example.

### CODE REVIEW

**Comment by sbis04** [comment]
I will also add a **Getting started** guide with step-by-step instruction to this page in a separate PR.

**Comment by sbis04** [comment]
@huan is the PR alright? Once this is merged I will send a PR by adding the **Getting started** guide. Also I have a plan to add interactive **CodeSandbox** to this page, so that beginners can try out the bot directly on the docs.

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thanks for fixing the Wechaty Vorpal examples in our docs! Appreciate it.

Looking forward to the interactive CodeSandbox examples!

**Pull request merged**
