### PR TITLE
[GSoD 2021] Converted all Jekyll blog contributors images to webp

### LINKED ISSUE #1035: Enforce all images in wechaty website to use `.webp` format
Because the `.webp` format has lots of advantages and the [safari has supported it last year](https://www.macrumors.com/2020/06/22/webp-safari-14/) which means all the modern browsers will be able to compatible with it.

The plan is:

1. write a new unit test to disable all other image extensions. like: `.gif`, `.jpg`, `.png`, etc.
2. convert all the existing image files in our repo to `.webp` and update all the references in all files.

Please feel free to let me know if you have any comments by replying to this issue.

- [x] Convert all Jekyll blog contributors' images to `.webp` format and updated the corresponding links.
- [x] Convert all Jekyll blog posts images to `.webp` format and updated the corresponding links:
  - #1328
- [ ] Convert all Docusaurus site images to `.webp` format and updated the corresponding links.
- [ ] Convert all miscellaneous images to `.webp` format which are in the root directory of the repository.
- [ ] Make sure all necessary images are converted to `.webp` format and pages do not have broken links. Also, update <https://github.com/wechaty/wechaty.js.org/blob/master/tests/workaround.ts> accordingly.

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #1035
Related: #1012

Screenshot 2021-07-13 at 8 33 06 AM

### CODE REVIEW

**Comment by iamrajiv** [comment]
Hi, @huan can take a look at this PR. Also, all things are correct not don know why CI is saying `Error: should exist on GitHub`. Is there any limit on the number of changes in a single PR?

**Comment by nibble0101** [comment]
> Hi, @huan can you take a look at this PR. Also, all things are correct not don know why CI is saying `Error: should exist on GitHub`. Is there any limit on the number of changes in a single PR?

It seems that error is due to the fact that actual requests are being made to GitHub when running these tests. You can look at [these lines of code](https://github.com/wechaty/wechaty.js.org/blob/master/src/jekyll/is-url-exist.ts#L43-L55). Given the number of files you have changed (I suspect you changed the image formats for all contributors  to `webp`), the number of requests made to GitHub while running the tests is as many as the number of contributors. That is why after making 40 - 60 requests to GitHub, you will start getting  `statusText` of `too many requests` in the response making the tests to start failing. Ideally a person adding him/herself as contributor will necessitate making one fetch request when testing the existence of their account. The kind of changes in your PR was perhaps never envisaged.

You can add the code below [here](https://github.com/wechaty/wechaty.js.org/blob/master/src/jekyll/is-url-exist.ts#L54) and then run the tests on your computer.
```js
console.log('statusText', response.statusText)
console.log('ok', response.ok)
```
When I did the same, this is what I got. Though you might need to comment out [these lines of code](https://github.com/wechaty/wechaty.js.org/blob/master/tests/jekyll/contributor-profile.spec.ts#L129-L130) to avoid having a congested terminal.
image

I believe one of the solutions could be to split the PR so that each PR is changing image format for not more than 50 contributors, though I have not really tried whether that will work or not. Another option is to merge ignoring the failing tests. 
yes splitting the PR might help out @iamrajiv

**Comment by iamrajiv** [comment]
Thanks for the insights @nibble0101. Yeah, you are correct it's happening because of too many requests at one time. Splitting this PR into more PRs will be a difficult task. The best approach if we can ignore failing tests.

**Review by huan — APPROVED** [review]
LGTM

Thank you so much for converting all of those image files to `.webp`, it's really a great improvement and for our website!

**Comment by huan** [comment]
@iamrajiv Yes, I agree with you that the best approach is ignoring the failing tests, and thanks to @nibble0101 for pointing the reason for the failing CI.

I noticed that there are two files are conflict with the main branch, please fix those conflicts then I believe we will be able to merge this epic PR!

**Comment by iamrajiv** [comment]
@huan Resolved the conflicts. LGTM!

**Comment by iamrajiv** [comment]
@huan I think we can merge this because if we wait merge conflict can happen.

**Comment by huan** [comment]
@iamrajiv thanks for the notification.

Let's merge this PR first, and please have a double check after this PR has been published.

Appreciate to all your efforts to webpify our images!

**Pull request merged**
