### PR TITLE
Added tutorial for using vanilla-redux with wechaty

### PR DESCRIPTION
**Pull request by shwetalsoni**
Screenshot from 2021-08-04 13-56-29
Screenshot from 2021-08-04 13-56-42
Screenshot from 2021-08-04 13-56-54
Screenshot from 2021-08-04 13-57-05
Screenshot from 2021-08-04 13-57-20
Screenshot from 2021-08-04 13-57-32
Screenshot from 2021-08-04 13-57-51
Screenshot from 2021-08-04 13-58-03
Screenshot from 2021-08-04 13-58-16

### CODE REVIEW

**Comment by shwetalsoni** [comment]
Tag #891

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
proofread

**Review by proudofsimin — APPROVED** [review]

**Review by sbis04 — APPROVED** [review]

**Comment by shwetalsoni** [comment]
@Rohitesh-Kumar-Jain and @proudofsimin please add this PR to the merging list.

Thank you :)

**Review by lijiarui — APPROVED** [review]
LGTM

**Pull request merged**
