### PR TITLE
基于wechaty开发的医疗小助手

### PR DESCRIPTION
**Pull request by smartnikocj**
Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

### CODE REVIEW

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

1. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Comment by huan** [comment]
It seems that we still have the following issues:

```sh
jekyll/_contributors/smartnikocj.md:15:33 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:81:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:81 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- 轮科医生排班与考勤"]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:82:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:83:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:84:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:85:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:86:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:87:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:88:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
jekyll/_posts/2022-02-02-wechaty-medical-bot.md:94 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

I'd like to suggest that you run the `npm test` locally to fix those problems more efficiently, esp., there will be more tests after the markdown linting.

**Comment by smartnikocj** [comment]
> It seems that we still have the following issues:
> 
> ```shell
> jekyll/_contributors/smartnikocj.md:15:33 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:81:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:81 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- 轮科医生排班与考勤"]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:82:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:83:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:84:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:85:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:86:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:87:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:88:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> jekyll/_posts/2022-02-02-wechaty-medical-bot.md:94 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
> ```
> 
> I'd like to suggest that you run the `npm test` locally to fix those problems more efficiently, esp., there will be more tests after the markdown linting.

Thanks, I try my best to run `npm test` locally.

**Comment by smartnikocj** [comment]
> > It seems that we still have the following issues:
> > ```shell
> > jekyll/_contributors/smartnikocj.md:15:33 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:81:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:81 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- 轮科医生排班与考勤"]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:82:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:83:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:84:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:85:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:86:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:87:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:88:1 MD007/ul-indent Unordered list indentation [Expected: 0; Actual: 2]
> > jekyll/_posts/2022-02-02-wechaty-medical-bot.md:94 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'd like to suggest that you run the `npm test` locally to fix those problems more efficiently, esp., there will be more tests after the markdown linting.
> 
> Thanks, I try my best to run `npm test` locally.

HELP WANTED!

I run `npm install` and then `npm test`, errors were noticed. 

Here is the log.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'H:\\Software\\nodejs\\node.exe',
1 verbose cli   'H:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle wechaty.js.org@0.10.58~prelint: wechaty.js.org@0.10.58
6 info lifecycle wechaty.js.org@0.10.58~lint: wechaty.js.org@0.10.58
7 verbose lifecycle wechaty.js.org@0.10.58~lint: unsafe-perm in lifecycle true
8 verbose lifecycle wechaty.js.org@0.10.58~lint: PATH: H:\Software\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\Software\Python\Pycharm\wechaty.js.org\node_modules\.bin;H:\Software\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\Software\Python\Pycharm\wechaty.js.org\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\1.5\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\1.5\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;H:\Software\Lenovo\Bluetooth Software\;H:\Software\Lenovo\Bluetooth Software\syswow64;H:\Software\Python\Python38\Scripts;H:\Software\phantomjs\bin;H:\Software\Python\Python38\;H:\Software\Git\cmd;H:\Software\nodejs\;H:\Software\7-Zip;H:\Software\PostgreSQL\12\bin;H:\Software\scrcpy-v1.17\adb.exe;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;H:\Software\Python\Python38\Scripts\;H:\Software\Python\Python38\;C:\Users\SMarT\AppData\Local\BypassRuntm;C:\Users\SMarT\AppData\Roaming\npm
9 verbose lifecycle wechaty.js.org@0.10.58~lint: CWD: H:\Software\Python\Pycharm\wechaty.js.org
10 silly lifecycle wechaty.js.org@0.10.58~lint: Args: [ '/d /s /c', 'npm-run-all lint:es lint:ts lint:md lint:fn lint:yml' ]
11 silly lifecycle wechaty.js.org@0.10.58~lint: Returned: code: 1  signal: null
12 info lifecycle wechaty.js.org@0.10.58~lint: Failed to exec lint script
13 verbose stack Error: wechaty.js.org@0.10.58 lint: `npm-run-all lint:es lint:ts lint:md lint:fn lint:yml`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (H:\Software\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (H:\Software\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid wechaty.js.org@0.10.58
15 verbose cwd H:\Software\Python\Pycharm\wechaty.js.org
16 verbose Windows_NT 6.1.7601
17 verbose argv "H:\\Software\\nodejs\\node.exe" "H:\\Software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error wechaty.js.org@0.10.58 lint: `npm-run-all lint:es lint:ts lint:md lint:fn lint:yml`
22 error Exit status 1
23 error Failed at the wechaty.js.org@0.10.58 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I google it, but still failed to fix the problem. And I think I can push and wait the CI help me to check whether there are errors. Howerer, get error again when I push my content. See below. 

```
NotSupportedException encountered. ServicePointManager ��֧�־��� socks5 �����Ĵ��� npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wechaty.js.org@0.10.58 lint:es: `eslint "src/**/*.ts" "tests/**/*.spec.ts" --ignore-pattern tests/fixtures/` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the wechaty.js.org@0.10.58 lint:es script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\SMarT\AppData\Roaming\npm-cache\_logs\2022-02-03T03_07_36_637Z-debug.log ERROR: "lint:es" exited with 1. npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wechaty.js.org@0.10.58 lint: `npm-run-all lint:es lint:ts lint:md lint:fn lint:yml` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the wechaty.js.org@0.10.58 lint script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\SMarT\AppData\Roaming\npm-cache\_logs\2022-02-03T03_07_36_679Z-debug.log Failed to exec pre-push hook script failed to push some refs to 'https://github.com/smartnikocj/wechaty.js.org.git'
```

**Comment by huan** [comment]
It seems that you are running into the following 2 issues:

1. Our testing script is not support windows now. You need either to run it under Linux/Mac, or just push it to your GitHub branch to let the GitHub Actions to run it for you (which is slower but workable)
2. Your internet connection seems is inside the china intranet. Use a VPS our side of China will probably solve your problem.

**Comment by smartnikocj** [comment]
> It seems that you are running into the following 2 issues:
> 
> 1. Our testing script is not support windows now. You need either to run it under Linux/Mac, or just push it to your GitHub branch to let the GitHub Actions to run it for you (which is slower but workable)
> 2. Your internet connection seems is inside the china intranet. Use a VPS our side of China will probably solve your problem.

Thanks Huan. 
That is what I am thinking now. I want to push it to my Github and let the Action help me to check error. 
But, I still get error no matter I use VPS or not. The PUSH was ok before I run `npm install` yesterday. 
```
NotSupportedException encountered. ServicePointManager ��֧�־��� socks5 �����Ĵ��� npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wechaty.js.org@0.10.58 lint:es: `eslint "src/**/*.ts" "tests/**/*.spec.ts" --ignore-pattern tests/fixtures/` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the wechaty.js.org@0.10.58 lint:es script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\SMarT\AppData\Roaming\npm-cache\_logs\2022-02-03T03_46_58_664Z-debug.log ERROR: "lint:es" exited with 1. npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wechaty.js.org@0.10.58 lint: `npm-run-all lint:es lint:ts lint:md lint:fn lint:yml` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the wechaty.js.org@0.10.58 lint script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\SMarT\AppData\Roaming\npm-cache\_logs\2022-02-03T03_46_58_708Z-debug.log Failed to exec pre-push hook script failed to push some refs to 'https://github.com/smartnikocj/wechaty.js.org.git'
```

**Comment by huan** [comment]
try use

```sh
NO_HOOK=1 git push
```

**Comment by smartnikocj** [comment]
> 

Sad, I can not run this command in Pycharm.

**Comment by smartnikocj** [comment]
> try use
> 
> ```shell
> NO_HOOK=1 git push
> ```

```
fatal: NotSupportedException encountered.  
ServicePointManager 不支持具有 socks5 方案的代理。
```
I think something went wrong after running `npm install`. It changes my proxy?

**Comment by smartnikocj** [comment]
after trying everything, still get error:
```
Push failed Npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wechaty.js.org@0.10.58 lint:es: `eslint "src/**/*.ts" "tests/**/*.spec.ts" --ignore-pattern tests/fixtures/` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the wechaty.js.org@0.10.58 lint:es script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\SMarT\AppData\Roaming\npm-cache\_logs\2022-02-03T06_04_30_331Z-debug.log ERROR: "lint:es" exited with 1. npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! wechaty.js.org@0.10.58 lint: `npm-run-all lint:es lint:ts lint:md lint:fn lint:yml` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the wechaty.js.org@0.10.58 lint script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\SMarT\AppData\Roaming\npm-cache\_logs\2022-02-03T06_04_30_374Z-debug.log Failed to exec pre-push hook script failed to push some refs to 'https://github.com/smartnikocj/wechaty.js.org.git'
```

**Comment by smartnikocj** [comment]
Finally, I use `git bash` to push sucessfully.  Run `NO_HOOK=1 git push` in `git bash`

**Comment by smartnikocj** [comment]
I think I should wait the maintainer to approve my application because this is my first contribution. @huan , thanks.

**Comment by huan** [comment]
Yeah, now GitHub requires approve manually Everytime for the PR to run the actions, which is not very convenient.

**Comment by smartnikocj** [comment]
```
1..20
# failed 1 of 20 tests
# time=40[342](https://github.com/wechaty/wechaty.js.org/runs/5048634596?check_suite_focus=true#step:7:342).972ms
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
ERROR: "test:unit" exited with 1.
Error: Process completed with exit code 1.
```

What should I do now? Sorry, I can not figure out which step is wrong.

**Comment by huan** [comment]
See: https://github.com/wechaty/wechaty.js.org/runs/5048634596?check_suite_focus=true#step:7:125

>         not ok 1 - "jekyll/assets/2022/02-wechaty-medical-bot/title-image.webp" (width: 2000, size: 76858) exceed the maximum limitation: width<=1920 size<=1048576

```
not ok 8 - tests/assets-image-type-size.spec.ts # time=4[126](https://github.com/wechaty/wechaty.js.org/runs/5048634596?check_suite_focus=true#step:7:126).741ms
  ---
  env: {}
  file: tests/assets-image-type-size.spec.ts
  timeout: 60000
  command: /opt/hostedtoolcache/node/16.13.2/x64/bin/node
  args:
    - tests/assets-image-type-size.spec.ts
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/runner/work/wechaty.js.org/wechaty.js.org
  exitCode: 1
  ...
{
    # Subtest: image size should be fit for the web (no more than 1MB and 1920x1080)
        not ok 1 - "jekyll/assets/2022/02-wechaty-medical-bot/title-image.webp" (width: 2000, size: 76858) exceed the maximum limitation: width<=1920 size<=1048576
          ---
          at:
            line: 74
            column: 9
            file: file:///home/runner/work/wechaty.js.org/wechaty.js.org/tests/assets-image-type-size.spec.ts
            type: Test
          stack: |
            Test.<anonymous> (file://tests/assets-image-type-size.spec.ts:74:9)
            runMicrotasks (<anonymous>)
          ...
        
        ok 2 - 1700 files checked
        1..2
        # failed 1 of 2 tests
    not ok 1 - image size should be fit for the web (no more than 1MB and 1920x1080) # time=3742.783ms
```

I believe this PR will be OK to be merged after we fixed this size issue.

**Comment by smartnikocj** [comment]
```
not ok 8 - tests/assets-image-type-size.spec.ts # time=4[126](https://github.com/wechaty/wechaty.js.org/runs/5048634596?check_suite_focus=true#step:7:126).741ms
  ---
  env: {}
  file: tests/assets-image-type-size.spec.ts
  timeout: 60000
  command: /opt/hostedtoolcache/node/16.13.2/x64/bin/node
  args:
    - tests/assets-image-type-size.spec.ts
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/runner/work/wechaty.js.org/wechaty.js.org
  exitCode: 1
  ...
{
    # Subtest: image size should be fit for the web (no more than 1MB and 1920x1080)
        not ok 1 - "jekyll/assets/2022/02-wechaty-medical-bot/title-image.webp" (width: 2000, size: 76858) exceed the maximum limitation: width<=1920 size<=1048576
          ---
          at:
            line: 74
            column: 9
            file: file:///home/runner/work/wechaty.js.org/wechaty.js.org/tests/assets-image-type-size.spec.ts
            type: Test
          stack: |
            Test.<anonymous> (file://tests/assets-image-type-size.spec.ts:74:9)
            runMicrotasks (<anonymous>)
          ...
        
        ok 2 - 1700 files checked
        1..2
        # failed 1 of 2 tests
    not ok 1 - image size should be fit for the web (no more than 1MB and 1920x1080) # time=3742.783ms
    
    # Subtest: we enforce all image type to .webp (#1035)
        ok 1 - all image files are .webp
        1..1
    ok 2 - we enforce all image type to .webp (#1035) # time=378.649ms
    
    1..2
    # failed 1 of 2 tests
    # time=4126.741ms
}
```
Get it! image size should be fit for the web (no more than 1MB and 1920x1080).

**Comment by smartnikocj** [comment]
> See: https://github.com/wechaty/wechaty.js.org/runs/5048634596?check_suite_focus=true#step:7:125
> 
> > ```
> >     not ok 1 - "jekyll/assets/2022/02-wechaty-medical-bot/title-image.webp" (width: 2000, size: 76858) exceed the maximum limitation: width<=1920 size<=1048576
> > ```
> 
> ```
> not ok 8 - tests/assets-image-type-size.spec.ts # time=4[126](https://github.com/wechaty/wechaty.js.org/runs/5048634596?check_suite_focus=true#step:7:126).741ms
>   ---
>   env: {}
>   file: tests/assets-image-type-size.spec.ts
>   timeout: 60000
>   command: /opt/hostedtoolcache/node/16.13.2/x64/bin/node
>   args:
>     - tests/assets-image-type-size.spec.ts
>   stdio:
>     - 0
>     - pipe
>     - 2
>   cwd: /home/runner/work/wechaty.js.org/wechaty.js.org
>   exitCode: 1
>   ...
> {
>     # Subtest: image size should be fit for the web (no more than 1MB and 1920x1080)
>         not ok 1 - "jekyll/assets/2022/02-wechaty-medical-bot/title-image.webp" (width: 2000, size: 76858) exceed the maximum limitation: width<=1920 size<=1048576
>           ---
>           at:
>             line: 74
>             column: 9
>             file: file:///home/runner/work/wechaty.js.org/wechaty.js.org/tests/assets-image-type-size.spec.ts
>             type: Test
>           stack: |
>             Test.<anonymous> (file://tests/assets-image-type-size.spec.ts:74:9)
>             runMicrotasks (<anonymous>)
>           ...
>         
>         ok 2 - 1700 files checked
>         1..2
>         # failed 1 of 2 tests
>     not ok 1 - image size should be fit for the web (no more than 1MB and 1920x1080) # time=3742.783ms
> ```
> 
> I believe this PR will be OK to be merged after we fixed this size issue.

Get it! I have modified the size of the image.

**Comment by huan** [comment]
Let's see!

**Comment by smartnikocj** [comment]
> Let's see!

Cool and excited! It turns GREEN!! My first PR, I believe I will contribute more!! @huan

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> [](https://github.com/wechaty)You've invited SMarT to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Pull request merged**
