### PR TITLE
[GSoD 2021] Added blogs on gRPC and OpenAPI

### PR DESCRIPTION
**Pull request by iamrajiv**
Related: #1012

Screenshot 2021-06-08 at 1 05 36 AM
Screenshot 2021-06-08 at 1 05 31 AM

### CODE REVIEW

**Comment by iamrajiv** [comment]
@huan @Rohitesh-Kumar-Jain @proudofsimin Please take a look.

**Comment by proudofsimin** [comment]
Hi @iamrajiv, 
I have browsed your PR carefully and felt that I'm in an awkward situation. If it's in Docs I might request some modifications about the structure and writing style, but since it's in a blog post that I would suggest that you keep your style and stay a more conversational way to the readers. How do you think?

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Perfect PR : clean commit history, properly based, relevant screenshots, PR good in scope.

**Comment by iamrajiv** [comment]
@proudofsimin @lijiarui Can you take a look.

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for sharing those great blog posts for introducing the gRPC and OpenAPI to the community!

**Pull request merged**
