### PR TITLE
Update puppet services compatibility

### PR DESCRIPTION
**Pull request by Soumi7**
# Update puppet services compatibility

## Screenshots 

Screenshot from 2021-09-11 11-38-16

Screenshot from 2021-09-11 11-38-19

Screenshot from 2021-09-11 11-38-26

Screenshot from 2021-09-11 11-38-30

### CODE REVIEW

**Comment by Rohitesh-Kumar-Jain** [comment]
hi @Soumi7 can you pls explain what this PR is about, and what are you doing in this PR? I can see just one line being added and a lot of content being removed.

**Review by Rohitesh-Kumar-Jain — COMMENTED** [review]
Pls let us more about this PR, and what updation are you doing : )

**Comment by Soumi7** [comment]
The chinese is changed to english here. @Rohitesh-Kumar-Jain

**Review by shraddhavp — APPROVED** [review]

**Comment by Rohitesh-Kumar-Jain** [comment]
> The chinese is changed to english here. @Rohitesh-Kumar-Jain

I am unable to see either Chinese or English addition in here 😅

**Review by proudofsimin — COMMENTED** [review]
Could you change the following translations:
1. Pull people into the group-> add people in the group
2. Kick out of the group -> remove people out of the group
3. Group entry event / outlier. Hi @huan I'm not sure what it means by "入群事件“ and “離群事件" so not sure if the translation is correct. I guess it should be "Join group request" and "Leave group request" instead?
4. Modification notes -> revise notes
5. Pass friends automatically -> Automatically add friends

**Comment by Soumi7** [comment]
> > The chinese is changed to english here. @Rohitesh-Kumar-Jain
> 
> I am unable to see either Chinese or English addition in here 😅

Not sure why that is happening 😅. If you go to edit, you will be able to see the changes.

**Comment by Soumi7** [comment]
@proudofsimin Made the changes as you suggested except point 3, waiting for @huan 's reply on that.

**Comment by Soumi7** [comment]
> Could you change the following translations:
> 
> 1. Pull people into the group-> add people in the group
> 2. Kick out of the group -> remove people out of the group
> 3. Group entry event / outlier. Hi @huan I'm not sure what it means by "入群事件“ and “離群事件" so not sure if the translation is correct. I guess it should be "Join group request" and "Leave group request" instead?
> 4. Modification notes -> revise notes
> 5. Pass friends automatically -> Automatically add friends

@huan Could you please look at point 3 here?

**Comment by lijiarui** [comment]
> Group entry event / outlier. Hi @huan I'm not sure what it means by "入群事件“ and “離群事件" so not sure if the translation is correct. I guess it should be "Join group request" and "Leave group request" instead?

Hi, @proudofsimin I think "Join group event" and "Leave group event" will be better, since they are events, instead of requests. All of them are better than group entry/outlier.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
For some reason I wasn't able to see English additions 😅

**Review by proudofsimin — APPROVED** [review]

**Pull request merged**
