### PR TITLE
13-18 JuziBot项目开发-期初报告-智能信息助理

### PR DESCRIPTION
**Pull request by tianrking**

### CODE REVIEW

**Review by qhduan — DISMISSED** [review]
LGTM

**Comment by tianrking** [comment]
Fixed a typo, the format has not changed , npm run test passed 😊

**Review by zhihuifanqiechaodan — DISMISSED** [review]

**Comment by huan** [comment]
@zhihuifanqiechaodan Thank you very much for helping approve the blog PR!

I have added you to the @wechaty/editors team and then you will have write privilege, so that:

1. Your approval will be counted as 1 of the 3 requirements (vote) before merging the PR
2. You can approve the GitHub Actions when a PR has been submitted or updated.

Please feel free to let me know if you need other privileges when you think they can help our community.

Appreciate your efforts in helping others in our community!

**Comment by zhihuifanqiechaodan** [comment]
> @zhihuifanqiechaodan Thank you very much for helping approve the blog PR!
> 
> I have added you to the @wechaty/editors team and then you will have write privilege, so that:
> 
> 1. Your approval will be counted as 1 of the 3 requirements (vote) before merging the PR
> 2. You can approve the GitHub Actions when a PR has been submitted or updated.
> 
> Please feel free to let me know if you need other privileges when you think they can help our community.
> 
> Appreciate your efforts in helping others in our community!

Great. I'm glad I was able to help

**Review by qhduan — DISMISSED** [review]
LGTM

**Review by zhihuifanqiechaodan — APPROVED** [review]

**Review by qhduan — APPROVED** [review]

**Pull request closed without merging**
