### PR TITLE
Tom blog

### PR DESCRIPTION
**Pull request by quantumFlame**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ √] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [ √] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ √] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [√ ] Add `<!--more-->` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

### CODE REVIEW

**Comment by huan** [comment]
It's great to read your blog, I'd like to invite you to join the Python Wechaty project at this very early stage so that you can be easily stay aligned with the latest Wechaty ecosystem.

**Comment by huan** [comment]
@quantumFlame Cloud you please add your self as an author to the author data file at <https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml> with your GitHub username?

And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

**Comment by quantumFlame** [comment]
> @quantumFlame Cloud you please add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username?
> 
> And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

Thanks! Author info updated.

**Comment by quantumFlame** [comment]
> It's great to read your blog, I'd like to invite you to join the Python Wechaty project at this very early stage so that you can be easily stay aligned with the latest Wechaty ecosystem.

Thanks for the invitation! I would be happy to join if you don't mind I might not be able to afford much time for the project since I am actually busy with many scheduled things.

**Review by huan — APPROVED** [review]
Thanks for sharing your great project, it's fantastic!

**Comment by huan** [comment]
@quantumFlame I have invited you to join the Wechaty Contributor Team on GitHub, please accept it and also add my wechat. I'd like to invite you to join our Wechaty Contributor WeChat group too.

> You've invited quantumFlame to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

**Comment by lijiarui** [comment]
@quantumFlame Could you add my wechat: `ruirui_0914` And I would like to invite you to wechaty contributor group.

Thanks!

**Pull request merged**
