### PR TITLE
Send and receive files

### PR DESCRIPTION
**Pull request by abhishek-iiit**
## Added how to send and receive file guide
Screenshot from 2021-07-22 22-24-40
Screenshot from 2021-07-22 22-24-50

### CODE REVIEW

**Comment by abhishek-iiit** [comment]
Linked to #896

**Review by proudofsimin — APPROVED** [review]
Fabulous. Your improvement is very significant :) Well done!

**Review by Rohitesh-Kumar-Jain — CHANGES_REQUESTED** [review]
> The steps outlined here mainly focus on working with Javascript, but user are free to switch between any languages.

This line needs some changes, either use "the user is" or "users are ..... language"

**Review by vasvi-sood — APPROVED** [review]
This PR looks Great to me!

**Comment by abhishek-iiit** [comment]
Changes done as suggested :)

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by huan — APPROVED** [review]
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

**Comment by Rohitesh-Kumar-Jain** [comment]
@abhishek-iiit I would be glad if you may solve merge conflicts and we proceed towards the merge : )

**Comment by abhishek-iiit** [comment]
Merging PR with no conflicts and 4 approvals :)

**Pull request merged**
