### PR TITLE
Added first two section styling (Draft)

### PR DESCRIPTION
**Pull request by arnabiscreating**
Issue Number ( #912 )
This commit comprises of the first two sections of the CSS file for the Wechaty landing page and is a draft PR for review purpose.
We will add more sections and files for further assessment in this PR, once they have been reviewed and cleared.
Thank you

### CODE REVIEW

**Comment by sajen-k** [comment]
@huan We have completed the integration of the new landing page with the docusaurus and tested locally in wechaty.js.org repo and everything is working well without any issues.

So can we start producing our atomic PRs as 1 PR for 1 component and a seperate PRs for CSS. 

Can I put a single draft PR in a new branch which contain all of our work code for the new landing page so that you can pull the code and test it locally then we can close the that single draft PR and once you finish testing then we can produce our PRs as 1 PR for 1 component and a sepreate PRs for CSS. whats you thoughts on this?

**Comment by huan** [comment]
Hi @encodeArnab ,

It's great to hear that we are ready to submit the atomic PR for the landing page!

For the whole landing page will be lots of changes, my suggestion would be:

> Send each text blocks in separate PR first, so that we can review the sentences first.

For the layout and the CSS related effects, I think they should be inline with each PR so that we can see the changes decoupled with any of other PRs.

After we have accepted all the PRs, we can move all the inline CSS to a separate file, as well as any JS files (if there's any)

If we can follow my suggestion above, I believe we can focus on the content for our landing page first, then the images, and at least the layout, CSS colors, js components, etc.

Please feel free to let me know if you have any questions, and I hope we can have all the atomic, decoupled PRS soon!

BTW please also feel free to create a branch with a draft PR for your convenience. However let's focus on the atomic and decoupled PRs only.

**Comment by arnabiscreating** [comment]
Hi @huan,
thank you for your suggestion we will work on having decoupled and atomic PRs,
I will send a test PR in accordance with your suggestion and let me know if that works.

**Comment by sajen-k** [comment]
I'm closing this PR since, as @huan  mentioned, we have our atomic PRs up and running, and as this is a draft PR, it's no longer needed.

**Pull request closed without merging**
