### PR TITLE
https://github.com/kaiyuanshe/osschat/issues/156 add article for ossc…

### PR DESCRIPTION
**Pull request by hailiang-wang**
…hat autoreply

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.

### CODE REVIEW

**Review by wj-Mcat — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Link to

- https://github.com/kaiyuanshe/osschat/issues/156

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for sharing the OSSChat + Chatopera experiences to the community, they are veryvaluable!

**Pull request merged**
