### PR TITLE
Added a blog and author

### PR DESCRIPTION
**Pull request by crossly**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `<!--more-->` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

### CODE REVIEW

**Comment by lijiarui** [comment]
@lemonsX  Thanks, could you sign the CLA first?

**Comment by crossly** [comment]
@lijiarui Done.

**Review by huan — CHANGES_REQUESTED** [review]
We still need a teaser image for our blog post, please add it, thanks.

**Comment by crossly** [comment]
@huan Added.

https://github.com/Chatie/blog/pull/211/commits/33d60371803e1fc56ceeae3e53735429aaa10fe3

**Review by huan — APPROVED** [review]
Thanks, your post is great!

**Review by huan — APPROVED** [review]
LGTM

**Comment by lijiarui** [comment]
@lemonsX  Thanks for your fantastic blog, could you add my wechat: **ruirui_0914**, and I will invite you into Wechaty Contributor WeChat Group.

Also, I just invite in you into wechaty org, please join us by clicking https://github.com/wechaty

image

**Pull request merged**
