### PR TITLE
Updated links in tutorials overview page and removed empty pages from examples section

### PR DESCRIPTION
**Pull request by shwetalsoni**
These are the bots that we have created tutorials for. As mentioned by @huan  [here](https://github.com/wechaty/wechaty.js.org/issues/1133#issuecomment-911648403), we are skipping the left out advanced and professional bots.

Screenshot from 2021-09-04 17-05-06

### CODE REVIEW

**Review by sbis04 — APPROVED** [review]

**Comment by Rohitesh-Kumar-Jain** [comment]
why are we removing empty pages, can't they be left for future ?

**Review by Rohitesh-Kumar-Jain — COMMENTED** [review]
Do we really need to remove empty pages @proudofsimin

**Comment by shwetalsoni** [comment]
> why are we removing empty pages, can't they be left for future

> why are we removing empty pages, can't they be left for future ?

I think leaving empty pages won't be good. 
Also, the pages that I have removed, for those pages I have provided links to getting-started repo of wechaty in tutorials overview page, so that the user has somewhere to refer. So, after this leaving empty pages won't make sense ig. What do you think @Rohitesh-Kumar-Jain ?

**Comment by proudofsimin** [comment]
> Do we really need to remove empty pages @proudofsimin

I don't suggest we left anything unfinished to be published. It seems a bit too casual.

**Review by proudofsimin — APPROVED** [review]

**Review by huan — APPROVED** [review]
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

**Comment by shwetalsoni** [comment]
Tag #891

**Comment by lsmze** [comment]
🔥

**Pull request merged**
