### PR TITLE
Refactor ding dong bot under examples

### PR DESCRIPTION
**Pull request by shwetalsoni**
I have updated `ding dong`  bot under examples.
For the building bot section, I have referred to `running locally` page under getting started
Here's how the page looks like:

Screenshot from 2021-07-17 12-31-22
Screenshot from 2021-07-17 12-31-33
Screenshot from 2021-07-17 12-32-02
Screenshot from 2021-07-17 12-32-14

### CODE REVIEW

**Comment by shwetalsoni** [comment]
Tag #891

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Thanks for the refactoring : )

**Review by proudofsimin — APPROVED** [review]
Thank you.

**Review by sbis04 — APPROVED** [review]

**Comment by shwetalsoni** [comment]
@Rohitesh-Kumar-Jain and @proudofsimin I think this PR can be added to #1056.

**Comment by Rohitesh-Kumar-Jain** [comment]
> @Rohitesh-Kumar-Jain and @proudofsimin I think this PR can be added to #1056.

yes it can be

**Comment by lijiarui** [comment]
LGTM!

**Pull request merged**
