### PR TITLE
Added Polyglot Architecture image

### PR DESCRIPTION
**Pull request by shraddhavp**
Added new polyglot architecture image 

Architecure

### CODE REVIEW

**Review by Soumi7 — APPROVED** [review]
LGTM

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by proudofsimin — APPROVED** [review]

**Comment by shraddhavp** [comment]
@huan  can you please check the image and give feedback on the same ? Then I will be merging it

**Review by huan — CHANGES_REQUESTED** [review]
@shraddhavp Thanks for ping me!

Please follow my comments below, and then I believe it's ready to be merged.

1. remove `Typescript` from `Wechaty (Typescript, Go, Python,...)` because it's already in the left chart
1. rename `wechaty-puppet-padplus` to `wechaty-puppet-padlocal` because padplus was deprecated and the padlocal is the
 new star
1. rename `wechaty-puppet-puppeteer` to `wechaty-puppet-wechat` because we have renamed the repo & npm name in early t
his year
1. rename `wechaty-puppet-windows` to `wechaty-puppet-xp` because there is never a `windows` puppet exists, and we are
 working on the windows protocol with the `xp` puppet now
1. rename `Mac Protocol` to `Whatsapp`, and `wechaty-puppet-macpro` to `wechaty-puppet-whatsapp`.

**Comment by shraddhavp** [comment]
> @shraddhavp Thanks for ping me!
> 
> Please follow my comments below, and then I believe it's ready to be merged.
> 
> 1. remove `Typescript` from `Wechaty (Typescript, Go, Python,...)` because it's already in the left chart
> 2. rename `wechaty-puppet-padplus` to `wechaty-puppet-padlocal` because padplus was deprecated and the padlocal is the
>    new star
> 3. rename `wechaty-puppet-puppeteer` to `wechaty-puppet-wechat` because we have renamed the repo & npm name in early t
>    his year
> 4. rename `wechaty-puppet-windows` to `wechaty-puppet-xp` because there is never a `windows` puppet exists, and we are
>    working on the windows protocol with the `xp` puppet now
> 5. rename `Mac Protocol` to `Whatsapp`, and `wechaty-puppet-macpro` to `wechaty-puppet-whatsapp`.

yes sure @huan

**Comment by shraddhavp** [comment]
@huan  added new image with the changes requested

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for the updating!

**Pull request merged**
