### PR TITLE
Wechat bot in ten minutes

### PR DESCRIPTION
**Pull request by luweiCN**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `<!--more-->` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.github.io#contribute-guideline)

### CODE REVIEW

**Comment by lijiarui** [comment]
Please modify this blog as blog template required.

**Comment by lijiarui** [comment]
ping @luweiCN

**Comment by lijiarui** [comment]
@luweiCN Please modify this blog as a blog template required.

If this PR has no reply until the end of August, I will close this PR.

**Comment by luweiCN** [comment]
@lijiarui sorry just saw the message

**Comment by lijiarui** [comment]
Since we change the template or wechaty blog, we have a break change:

## Before
You should add your profile at `author.yml`

## After

Remove `author.yml`

### 1. Create a file at `_developers` named as `yourname.md` 

 `yourname` should be the same as the author name you put in the blog:
```
---
title: XX
date: XX
author: yourname
categories: XX
tags:
  - XX
image: XX
---
```
### 2. The file should begin with:
```
---
name: Jiarui LI (李佳芮)
site: https://lijiarui.github.io
bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
avatar: /assets/developers/lijiarui/avatar.png
email: rui@juzi.bot
twitter: https://weibo.com/u/2175505900
---
```

### 3. Example:

- lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
- It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

Looking forward to your profile file at the `_developers` folder!

**Comment by lijiarui** [comment]
@luweiCN  Please resolve the conflict and remove the useless file.

**Comment by lijiarui** [comment]
@luweiCN Please resolve the conflict and remove the useless files.

I will close this PR if this PR has no reply at the end of September.

**Comment by lijiarui** [comment]
@wj-Mcat  Please help @luweiCN posting his blog.

**Comment by wj-Mcat** [comment]
@luweiCN You can click the `Resolve Confilicts` at the bottom of this page, and try to make CI green.  Please complete this issue as soon as possible, thanks a lot. Wating for your new commits.

**Comment by wj-Mcat** [comment]
There is a conflicting file, please fix it so we can merge it. Thanks a lot.

**Comment by huan** [comment]
@wj-Mcat We are not using `_data/authors.yml` file anymore.

A developer profile should be placed in the `_developers/` directory.

**Comment by wj-Mcat** [comment]
@luweiCN please pull your branch to add your profile to `_developers/` directory.

**Comment by luweiCN** [comment]
@wj-Mcat Sorry guys, just read your message. I will do it later today

**Comment by wj-Mcat** [comment]
@luweiCN Glad to hear that you will finish it this day. Wating for your new commit to fix it. 🎉

**Comment by huan** [comment]
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/07/02/wechat-bot-in-ten-minutes>

You've invited 芦苇 to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

1. I have invited you to join the Wechaty Contributor Team on our GitHub Wechaty Organization, please accept it by visiting <https://github.com/wechaty>
1. We have a WeChat room for Wechaty Contributors only, if you'd like to join, please contact @lijiarui on WeChat.

**Pull request merged**
