### PR TITLE
Updated world's shortest chatbot page under examples

### PR DESCRIPTION
**Pull request by shwetalsoni**
Screenshot from 2021-07-17 13-12-21
Screenshot from 2021-07-17 13-12-40

### CODE REVIEW

**Comment by shwetalsoni** [comment]
Tag #891

**Review by Rohitesh-Kumar-Jain — COMMENTED** [review]
Does anyone else think that we can use the deleted documentation in the future somewhere else? So maybe save that here #1089?

**Review by proudofsimin — COMMENTED** [review]
Hi, please correct me if I'm wrong. I have two questions for this.
1. Are we expected to see codesandbox for this? Or you will add it in another PR?
2. Do we need the installation like the starter bot? If yes, please add to it. 
Also we need a few sentences to describe and explain the code snippet in the usage part (otherwise it's more like notes but documents).
Thank you.

**Comment by shwetalsoni** [comment]
> Hi, please correct me if I'm wrong. I have two questions for this.
> 
> 1. Are we expected to see codesandbox for this? Or you will add it in another PR?
> 2. Do we need the installation like the starter bot? If yes, please add to it.
>    Also we need a few sentences to describe and explain the code snippet in the usage part (otherwise it's more like notes but documents).
>    Thank you.

Hii simin,
Actually, World's shortest chatbot is the example or we can say is more like a code snippet which demonstrates that you need minimum 6 lines of code to get started with wechaty. 
But yes, I agree with you I ''ll explain more what this code does, but it doesn't need any codeSandbox.

Thank you

**Comment by shwetalsoni** [comment]
Hii @proudofsimin, I have added some more info to it.

Screenshot from 2021-07-21 14-49-33

**Comment by shwetalsoni** [comment]
> Does anyone else think that we can use the deleted documentation in the future somewhere else? So maybe save that here #1089?

Hii @Rohitesh-Kumar-Jain, it can be useful. But here the overview.md file that I have deleted here was just redundant. I have already added overview for all tutorials in the tutorials overview page and these examples have been listed there. So there was no need to add overview again for it here.

**Review by proudofsimin — APPROVED** [review]
Thank you. This is helpful!

**Comment by shwetalsoni** [comment]
@Rohitesh-Kumar-Jain and @sbis04 Can you please review this PR. I think it's been a long time since this PR is created.

**Review by sbis04 — APPROVED** [review]

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by lijiarui — APPROVED** [review]
LGTM, but I think we should fix https://github.com/wechaty/wechaty.js.org/issues/1215 in a new PR.

**Comment by shwetalsoni** [comment]
> LGTM, but I think we should fix #1215 in a new PR.

I will create PR for #1215 once this PR #1104 is merged.

**Comment by lijiarui** [comment]
Approved, you can resolve the conflict, then I think @Rohitesh-Kumar-Jain would merge this PR.

**Comment by shwetalsoni** [comment]
> Approved, you can resolve the conflict, then I think @Rohitesh-Kumar-Jain would merge this PR.

Resolved the conflict @Rohitesh-Kumar-Jain

**Pull request merged**
