### PR TITLE
Update Puppet Providers : wechat

### PR DESCRIPTION
**Pull request by Soumi7**
This PR updates Puppet Providers : wechat in References.

References #890

Screenshot from 2021-07-17 19-19-04

Screenshot from 2021-07-17 19-19-10

Screenshot from 2021-07-17 19-19-18

Screenshot from 2021-07-17 19-19-21

Here some issues that were striked out I have removed them as they were not fixed.

### CODE REVIEW

**Review by shraddhavp — CHANGES_REQUESTED** [review]
@Soumi7  all looks good, I guess one small suggestion in the blogs section is you can remove the Chinese names and convert them to English itself as the  whole document is in English

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
LGTM

**Review by proudofsimin — CHANGES_REQUESTED** [review]
This is great, but could you replace the code snippet in the usage section with #1098 after it is merged?

**Comment by Soumi7** [comment]
> This is great, but could you replace the code snippet in the usage section with #1098 after it is merged?

Sure, I can do that.

**Review by huan — APPROVED** [review]
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

**Comment by Soumi7** [comment]
> This is great, but could you replace the code snippet in the usage section with #1098 after it is merged?

@proudofsimin #1098 has not been merged yet. We could merge this PR now and I can update it when #1098 gets merged.

**Review by shraddhavp — APPROVED** [review]
LGTM

**Comment by Rohitesh-Kumar-Jain** [comment]
ping for review @proudofsimin

**Review by proudofsimin — APPROVED** [review]

**Pull request merged**
