### PR TITLE
Improve Vorpal docs

### LINKED ISSUE #785: Improve the Vorpal tutorial page
I had added a few sections to the **Vorpal tutorial** page earlier, but this page still has some missing sections. Currently, it only tells the user to clone the repo and how to run the pre-built bot. But it doesn't tell the user how they can build the bot on their own (it lacks some technical details).

So, I would like to add some of the missing sections here and would like to structure it in the pattern I suggested in my [proposal](https://docs.google.com/document/d/1MD9CwO6BoB664J67ozfygBJUaawazay7dDpcXB3jJcY/edit?usp=sharing):

- [X] **Introduction** (improve this)
- [X] **Try out the bot**
- [X] **Requirements**
- [X] **Usage**
- [X] **Getting started** (refactor this a bit)
- [x] **Building the bot** (step-by-step guide for building the bot, with a `CodeSandbox` at the end having minimal code and `TODO` steps where users can try building the bot by themselves directly on the sandbox without installing any tools on their local system)
- [x] **Running the bot** (add this section - instructions are in `Getting started` section)
- [X] **Bot demonstration**
- [x] **Conclusion**
- [x] **References** (if any relevant references are there)

Please let me know your feedback about this.

### PR DESCRIPTION
**Pull request by sbis04**
Updated this docs page according to the structure.

## Changes

- Getting started modified
- Add **Building the bot** section
- Add **Running the bot** section
- Add **Conclusion** & **References**
- Add images to **Bot demonstration** section
- Editable CodeSandbox link for users to try building the bot without setting up their local dev environment
- Add a screenshot after running the bot

Fixes #785

### CODE REVIEW

**Review by huan — CHANGES_REQUESTED** [review]
Thanks for adding this great vorpal tutorial!

Could you please move all the images in this tutorial, from folder `docs/tutorials/` to `docs/tutorials/using-vorpal-with-wechaty/` sub-folder, so that those images can be better organized?

**Comment by sbis04** [comment]
I have updated the images location from `docs/tutorials/` to `docs/tutorials/using-vorpal-with-wechaty/`

**Comment by huan** [comment]
Awesome, merged!

**Comment by sbis04** [comment]
Tag: #891

**Pull request merged**
