### PR TITLE
added a blog (signed CLA)

### PR DESCRIPTION
**Pull request by hywhuangyuwei**
Fixes # 1.

- [x] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

### CODE REVIEW

**Comment by lijiarui** [comment]
Please make GitHub Pages CI  green and then I can review this PR.

**Comment by hywhuangyuwei** [comment]
> Please make GitHub Pages CI green and then I can review this PR.

Test passed.

**Comment by hywhuangyuwei** [comment]
@lijiarui Please help review it.

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/09/30/wechat-file-schedule-box-clafixed>

> You've invited hywhuangyuwei to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

1. I have invited you to join the Wechaty Contributor Team on our GitHub Wechaty Organization, please accept it by visiting <https://github.com/wechaty>
1. We have a WeChat room for Wechaty Contributors only, if you'd like to join, please contact @lijiarui on WeChat.

**Comment by huan** [comment]
Please see my point N.O. 2 in my previous post to learn how to join the contributors Wechat room.

**Comment by hywhuangyuwei** [comment]
> Please see my point N.O. 2 in my previous post to learn how to join the contributors Wechat room.

But I DO NOT know how to contact @lijiarui on Wechat.. I DO NOT have his/her Wechat ID.

**Comment by huan** [comment]
@hywhuangyuwei You can contact her by joining our Wechaty Developers' Home and then mention her by `@李佳芮`.

We have put a QR Code at https://wechaty.js.org, you can add our Friday BOT first then send `wechaty` to it so that it can invite you to join the developers' room.

**Pull request merged**
