### PR TITLE
feat: add highlight theme TANGO

### PR DESCRIPTION
**Pull request by chs97**
Add highlight theme TANGO
download from http://jwarby.github.io/jekyll-pygments-themes/languages/javascript.html

### CODE REVIEW

**Comment by huan** [comment]
Thank you @chs97 for adding this highlight theme for our website!

Could you please provide a before / after screenshot so that we will be able to compare them before we continue to review this PR?

**Comment by chs97** [comment]
after：
image
before：
image

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Your theme looks great, thank you very much for the contribution, appreciate it!

**Pull request merged**
