### PR TITLE
wechaty-bot

### PR DESCRIPTION
**Pull request by hd996**
added a blog (wechaty-bot)

### CODE REVIEW

**Comment by lijiarui** [comment]
Please sign the CLA first.

**Comment by hd996** [comment]
> Please sign the CLA first.
image
I have signed the CLA

**Comment by lijiarui** [comment]
It seems there has some problem of the account you sign the CLA. Please make sure they are the same email.

**Comment by lijiarui** [comment]
@Johnson-hd Please sing CLA first.

If this PR has no reply until the end of August, I will close this PR.

**Comment by lijiarui** [comment]
ping @Johnson-hd

**Comment by lijiarui** [comment]
@Johnson-hd I will close this PR if this PR has no reply at the end of September.

**Comment by lijiarui** [comment]
close this PR due to long time no reply.

**Pull request closed without merging**
