### PR TITLE
"基于Wechaty的个人助理，++生活效率&&有效对抗内卷"

### PR DESCRIPTION
**Pull request by sun2ot**
Please make sure to check the following boxes creating your pull request, thank you very much!

- [ ] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

### CODE REVIEW

**Comment by sun2ot** [comment]
I saw a merge button at the bottom of the page, so I clicked it. But it shows "merging is blocked". What do I need to do next? It would be my great honor to receive your reply.

**Comment by sun2ot** [comment]
> I saw a merge button at the bottom of the page, so I clicked it. But it shows "merging is blocked". What do I need to do next? It would be my great honor to receive your reply.

And I saw there is no green tick on the left of the "my_github_id.md" file I pushed to the "Jekyll / _contributors /" path. Is there anything wrong? If my question has caused any trouble to you, please forgive my ignorance.

**Comment by huan** [comment]
@yzh1255245824 Thank you very much for the sharing, your bot looks great!

Please make sure your PR can pass the CI (you can run `npm test` locally to confirm it before push), and we'd like to merge it when the CI turns green!

**Comment by sun2ot** [comment]
I am outdoors without a computer, but I am very excited to receive your reply. I just modified my MD file online through GitHub and submitted it, but I can't do NPM test at this time. I'm very sorry for the trouble caused.

**Comment by huan** [comment]
It seems there are some linting issues that need to be fixed:

- https://github.com/wechaty/wechaty.js.org/runs/4847297995?check_suite_focus=true#step:7:24

Please feel free to update here after you fixed them, and I hope you have a great day outdoor!

**Comment by sun2ot** [comment]
I have completed the "lint:md" test locally and passed. Thank you for the many times you went out of your way to test before.

**Comment by sun2ot** [comment]
After modifying the picture name, I forgot to modify the path of the MD file. At present, the problem has been fixed.

**Comment by sun2ot** [comment]
Ohhhhh，I have passed the CI Test. What should I do next to obtain a free token for developers?Thank you for your repeated help.

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for the sharing!

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited Hilbert Yi to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Pull request merged**
