### PR TITLE
First internship report of juzibot project

### PR DESCRIPTION
**Pull request by tianrking**

### CODE REVIEW

**Comment by tianrking** [comment]
https://github.com/wechaty/wechaty.js.org/pull/1459

**Review by qhduan — DISMISSED** [review]

**Review by zhihuifanqiechaodan — DISMISSED** [review]

**Comment by tianrking** [comment]
ping @zhihuifanqiechaodan  @qhduan @lijiarui

**Review by qhduan — APPROVED** [review]

**Review by zhihuifanqiechaodan — APPROVED** [review]

**Review by lijiarui — APPROVED** [review]
LGTM

**Review by huan — APPROVED** [review]
LGTM

**Comment by ncxiflows** [comment]
LGTM

**Pull request merged**
