### PR TITLE
Sixth post

### PR DESCRIPTION
**Pull request by Rohitesh-Kumar-Jain**
Screen Shot 2021-07-20 at 17 52 40-fullpage

### CODE REVIEW

**Review by proudofsimin — APPROVED** [review]

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for the sixth meeting blog post!

I'd like to invite you to help yourself to merge this PR, and as we discussed before, we should start merging PRs by technical writers themselves for quick iterating and move faster.

According to our settings of this repo: a PR will be able to be merged by the contributor who has write privileges after:

1. There's already 3 approvals from other contributors 
2. It passed the CI tests
3. It has no conflict

The technical writers team of GSoD'21 have all granted the write privilege I believe (they are all in the @wechaty/writers team).

So please try to merge this PR by yourself and let's see if the settings are correct, if it works, then I'd like to suggest that we can start merging those PRs which you believe it should be merged.

Please let me know what you think, thank you very much.

**Review by lijiarui — APPROVED** [review]
LGTM!

**Comment by Rohitesh-Kumar-Jain** [comment]
Hi @huan,

> So please try to merge this PR by yourself and let's see if the settings are correct, if it works, then I'd like to suggest that we can start merging those PRs which you believe it should be merged.

yes I was able to merge this after  merging the branch master into it

**Comment by Rohitesh-Kumar-Jain** [comment]
> So please try to merge this PR by yourself and let's see if the settings are correct, if it works, then I'd like to suggest that we can start merging those PRs which you believe it should be merged.

Unable to merge this one #962

Screenshot 2021-07-23 at 10 19 06 PM

**Comment by iamrajiv** [comment]
@Rohitesh-Kumar-Jain Closing the PR and opening again might work.

**Pull request merged**
