### PR TITLE
Update the Friend bot page

### PR DESCRIPTION
**Pull request by sbis04**
I have added content to the **Friend Bot** page under `Tutorials > Examples > Advanced` section. Also, I have updated the Friend bot link in `Tutorials > Overview` to point to the correct page.

The page looks like this:

Friend Bot

Tag #891

### CODE REVIEW

**Review by proudofsimin — APPROVED** [review]

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by shwetalsoni — APPROVED** [review]

**Comment by sbis04** [comment]
@Rohitesh-Kumar-Jain and @proudofsimin I think this PR can be added to #1056

**Comment by sbis04** [comment]
ping @Rohitesh-Kumar-Jain

**Review by lijiarui — APPROVED** [review]
Good job!

**Comment by Rohitesh-Kumar-Jain** [comment]
@sbis04  pls resolve the conflict, and then ping for merge

**Comment by sbis04** [comment]
@Rohitesh-Kumar-Jain I have fixed the merge conflict. Please merge this, after that I'll fix the merge conflict of #1155 as well

**Pull request merged**
