### PR TITLE
基于wechaty的智能聊天助手

### PR DESCRIPTION
**Pull request by chen-Aaron**

### CODE REVIEW

**Comment by lijiarui** [comment]
Please sign the CLA first and then we can review this PR.

**Comment by lijiarui** [comment]
ping @chen-Aaron

**Comment by lijiarui** [comment]
ping @chen-Aaron

**Comment by lijiarui** [comment]
ping @chen-Aaron

I will close this PR at the end of October if there isn't any reply.

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Comment by lijiarui** [comment]
ping @chen-Aaron

I will close this PR at the end of October if there isn't any reply.

**Comment by lijiarui** [comment]
ping @chen-Aaron

**Comment by huan** [comment]
ping @chen-Aaron

Could you please sign the CLA first, so that we can merge this PR and fix other issues later?

**Comment by huan** [comment]
This PR can not be merged anymore because the blog repo has been moved to https://github.com/wechaty/jekyll

Please feel free to create a new PR over there.

**Pull request closed without merging**
