### PR TITLE
Fix overview section of explanation section

### PR DESCRIPTION
**Pull request by nibble0101**
This PR fixes missing links and introduction to sub-sections of the Explanation section in the overview of explanation section.

### CODE REVIEW

**Review by chris-4444 — APPROVED** [review]
@nibble0101 @lijiarui 
Updated overview of the Explanation section. The following sections may be removed such as:
- Conversational - the contents here are discussed in [SDK & CUI](https://wechaty.js.org/docs/explanations/sdk-cui)
- Motivation - the contents here are discussed in [What can you do with Wechaty](https://wechaty.js.org/docs/what-can-you-do-with-wechaty)

**Comment by lijiarui** [comment]
> Updated overview of the Explanation section. The following sections may be removed such as:

> Conversational - the contents here are discussed in SDK & CUI
> Motivation - the contents here are discussed in What can you do with Wechaty

Hi, my suggestion is:

1. We should merge `Conversational` and `SDK & CUI` together and commit all of the related changes to this PR.
2. We should merge `Motivation` and `What can you do with Wechaty` together and commit all of the related changes to this PR.

Also, I think the sequence of the overview part is different from the sidebar, I suggest they should use the same sequence, or it may confuse the reader.

**Review by lijiarui — CHANGES_REQUESTED** [review]
> Updated overview of the Explanation section. The following sections may be removed such as:
>
> Conversational - the contents here are discussed in SDK & CUI
> Motivation - the contents here are discussed in What can you do with Wechaty

Hi, my suggestion is:

1. We should merge `Conversational` and `SDK & CUI` together and commit all of the related changes to this PR.
2. We should merge `Motivation` and `What can you do with Wechaty` together and commit all of the related changes to this PR.

Also, I think the sequence of the overview part is different from the sidebar, I suggest they should use the same sequence, or it may confuse the reader.

**Review by chris-4444 — APPROVED** [review]

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Comment by nibble0101** [comment]
> > Updated overview of the Explanation section. The following sections may be removed such as:
> > Conversational - the contents here are discussed in SDK & CUI
> > Motivation - the contents here are discussed in What can you do with Wechaty
> 
> Hi, my suggestion is:
> 
> 1. We should merge `Conversational` and `SDK & CUI` together and commit all of the related changes to this PR.
> 2. We should merge `Motivation` and `What can you do with Wechaty` together and commit all of the related changes to this PR.
> 
> Also, I think the sequence of the overview part is different from the sidebar, I suggest they should use the same sequence, or it may confuse the reader.

`Motivation` is already part of  `What can you do with Wechaty`.

**Review by proudofsimin — APPROVED** [review]

**Review by lijiarui — APPROVED** [review]
LGTM！ It's more clear now!

**Pull request merged**
