### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by gavinwang23**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

### CODE REVIEW

**Comment by gavinwang23** [comment]
make serve
run error in local

> sudo make serve
Password:
bundle exec jekyll serve --incremental
Configuration file: /Users/wangjunwei/code/wechaty.github.io/_config.yml
            Source: /Users/wangjunwei/code/wechaty.github.io
       Destination: /Users/wangjunwei/code/wechaty.github.io/_site
 Incremental build: enabled
      Generating... 
       Jekyll Feed: Generating feed for posts
  Dependency Error: Yikes! It looks like you don't have **kramdown-parser-gfm** or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown-parser-gfm' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2016-12-03-welcome-to-wechaty.md':
                    kramdown-parser-gfm
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    kramdown-parser-gfm
make: *** [serve] Error 1

so I add `gem 'kramdown-parser-gfm'` into Gemfile ,then run success

**Comment by huan** [comment]
Thanks for the contribution!

However, I have one question: our CI has always worked without any problem for the past months, so could you please have a double check to make sure this PR is real necessary for our system?

If it can be confirmed that it's required, then I'd like to merge it.

**Comment by gavinwang23** [comment]
It just reports an error in my local environment. I will run it on another computer later today. If it don’t report the error, I think it's unnecessary, and I will close this PR. Thank you for your suggestions!

**Comment by gavinwang23** [comment]
It's run success in my centos machine without `gem 'kramdown-parser-gfm'`, It's looks like unnecessary. haha

**Comment by huan** [comment]
Ok! Thanks for your confirmation.

Please feel free to send new PR if you find any other improving opportunities!

**Pull request closed without merging**
