### PR TITLE
Several alignment issues were resolved

### PR DESCRIPTION
**Pull request by arnabiscreating**
In the features, honours and awards sections, certain alignment issues were rectified.

### CODE REVIEW

**Review by iamrajiv — APPROVED** [review]

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Comment by Rohitesh-Kumar-Jain** [comment]
@sajenjeshan1222 if you approve we can merge this rightaway.

**Comment by sajen-k** [comment]
@Rohitesh-Kumar-Jain yes and I am waiting for the CI to turn green

**Review by sajen-k — APPROVED** [review]
LGTM

**Comment by shraddhavp** [comment]
LGTM

**Pull request merged**
