### PR TITLE
Henry blog

### PR DESCRIPTION
**Pull request by henryfanyiye**
Henry Blog

### CODE REVIEW

**Comment by wj-Mcat** [comment]
Sorry to keep you waiting so long , I will help you merge this pr.

**Review by wj-Mcat — APPROVED** [review]
LGTM 🎉

**Review by lijiarui — CHANGES_REQUESTED** [review]
@henryfanyiye Please resolve the confilct first.

**Comment by henryfanyiye** [comment]
> @henryfanyiye Please resolve the confilct first.

Solved

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/10/22/wechat-fanli-robot>

> You've invited henry.fan to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

1. I have invited you to join the Wechaty Contributor Team on our GitHub Wechaty Organization, please accept it by visiting <https://github.com/wechaty>
1. We have a WeChat room for Wechaty Contributors only, if you'd like to join, please contact @lijiarui on WeChat.

**Pull request merged**
