### PR TITLE
changed the side label for resolving the left bar navigation

### PR DESCRIPTION
**Pull request by shraddhavp**
this PR links to #919

### CODE REVIEW

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by proudofsimin — APPROVED** [review]

**Review by Soumi7 — APPROVED** [review]
Lgtm

**Comment by Soumi7** [comment]
@shraddhavp Could you provide the screenshots?

**Review by iamrajiv — APPROVED** [review]

**Review by lijiarui — CHANGES_REQUESTED** [review]
Do you mean you are changing the token to the gateway? Or you are just adding a gateway part?

Please don't remove the token part, since it is very important for the puppet ecosystem.

**Comment by shraddhavp** [comment]
> Do you mean you are changing the token to the gateway? Or you are just adding a gateway part?
> 
> Please don't remove the token part, since it is very important for the puppet ecosystem.

no not changing tokens only adding the gateway part @lijiarui

**Comment by shraddhavp** [comment]
@lijiarui  is there any changes to be made in this PR ?

**Review by lijiarui — APPROVED** [review]
LGTM, cheers!

**Pull request merged**
