### PR TITLE
add wechaty-puppet-official-account released blog.

### PR DESCRIPTION
**Pull request by wj-Mcat**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.  
    For example:  

    ``` md
    ---
    title: "Your Great Blog Title"
    author: your_github_id
    image: /assets/2020/08-your-blog-slug/teaser.jpg
    ---

    YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST
    ```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.md> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
  For excample:
  ```md
  ---
  name: Jiarui LI (李佳芮)
  site: https://lijiarui.github.io
  bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
  avatar: /assets/developers/lijiarui/avatar.png
  email: rui@juzi.bot
  twitter: https://weibo.com/u/2175505900
  ---
  ```
  Here is the example file:
  - lijiarui.md: https://github.com/wechaty/wechaty.github.io/blob/master/_developers/lijiarui.md
  - It will shown like this on wechaty blog: https://wechaty.github.io/developers/lijiarui/

To read more about the contribute guideline, visit: <https://github.com/wechaty/wechaty.js.org#contribute-guideline>

### CODE REVIEW

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thanks for this great blog, it's very valuable for our community to have this WeChat Official Account support announcement for our branding new wechaty-puppet-official-account!

It would be better if we can have an English version as our major version because this blog post will be our official article, which should in English as the first language for better globalization.

**Comment by wj-Mcat** [comment]
Of course, Considering the most devlopers, who want to use this puppet, are chinese, so should we keep the zh version, and I will post an english verison of the released blog ?

**Comment by huan** [comment]
> so should we keep the zh version, and I will post an English version of the released blog?

Ok, it's a great solution that we also publish a Chinese version of this blog.

Please go ahead with it, thank you very much.

**Comment by wj-Mcat** [comment]
OK, i will add an another post at later commits.

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
It's great to have our English version is the official account puppet announcement!

Thank you very much for your great effect for letting more developer to know our new puppet, please feel free to help yourself to merge this PR when you believe it's ready to go.

**Comment by wj-Mcat** [comment]
I have no permission to merge this pr.  @huan

**Comment by huan** [comment]
Yes, I forgot that the role of @wechaty/contributors in this repo is `Triage`.

Would you like to be added to the @wechaty/editors so that you can have the `Write` role here then you will be able to merge your PR by yourself and we can manage the PR of our website together?

If you want to, I'll count you in;
If you do not want to, I can merge this PR for you as well.

**Comment by wj-Mcat** [comment]
Yes, I do.  I'am glad to join wechaty/editors.

**Comment by huan** [comment]
Invited.

Welcome to @wechaty/editors! 

Please feel free to review and approve PRs for our website, we have lots of pending PRs in the past months waiting for review, we should review them to improve the qualities so that it can be qualified to be merged, then we can approve them and wait for the last merge.

**Review by lijiarui — APPROVED** [review]
LGTM

**Comment by wj-Mcat** [comment]
Ok, I will join to review blogs to improve the qualities to be merged.  🎉   🎉

**Pull request merged**
