### PR TITLE
Add Google Cloud Shell tutorial

### PR DESCRIPTION
**Pull request by sbis04**
I have added the Google Cloud Shell tutorial as a separate page under the Quick Start (previously both Gitpod and Google Cloud Shell tutorials were inside the same page making it harder for users to find). This is how it looks on the sidebar:

Screenshot 2021-06-04 at 1 02 26 PM

@shwetalsoni will be adding the Gitpod page content here.

Previously, the [Google Cloud Shell section](https://wechaty.js.org/docs/getting-started/quick-start#google-cloud-shell) of the Quick Start page wasn't formatted properly and it included duplicate information (because the users will get the full tutorial inside the cloud shell environment). 

So, I have just included the steps required for getting started with Google Cloud Shell. At the end, I have given a link to navigate to the running locally page and a link to a reference blog post.

The contents of the page:

CleanShot 2021-06-05 at 08 20 45

Tag: #891

### CODE REVIEW

**Review by proudofsimin — APPROVED** [review]
Wow nice. I like it.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Perfect PR : clean commit history, properly based, relevant screenshots, PR good in scope.

**Review by lijiarui — APPROVED** [review]
Good post!

**Review by huan — APPROVED** [review]

**Comment by lijiarui** [comment]
@sbis04 Please resolve the conflict first, then I will merge this PR.

**Comment by sbis04** [comment]
@lijiarui I have resolved the conflict

**Comment by lijiarui** [comment]
@sbis04  Thanks for resolving the conflict, but Github Action turn red, please fix CI and make CI green, then I will merge this PR.

**Comment by lijiarui** [comment]
Now it still have the conflict, please resolve the conflict. @sbis04

**Comment by sbis04** [comment]
@lijiarui Have made the CI green.

**Pull request merged**
