### PR TITLE
Add blog sqlite-wechat-assistant

### PR DESCRIPTION
**Pull request by moderncrazy**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `<!--more-->` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

### CODE REVIEW

**Comment by huan** [comment]
Nice post!

Please sign the CLA before we can merge this great article.

Thank you for sharing!

**Comment by geekeryoung** [comment]
I have signed the CLA, thank you for the merger.

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
I have invited you to join the GitHub Wechaty Contributor team, welcome to join us!

> You've invited GeekerYoung to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

And we also have a Wechaty Contributor WeChat group, please contact @lijiarui if you would like to join.

**Pull request merged**
