### PR TITLE
GSoD 2021 team proposal: Reconstruct Landing Page with value proposition (Sajen Sarvajith and Arnab Saha)

### PR DESCRIPTION
**Pull request by sajen-k**
We have completed the blog post with our video presentation for Reconstruct Landing Page with value proposition GSoD 2021.

### CODE REVIEW

**Comment by sajen-k** [comment]
@huan we have completed our team project proposal blog post with video presentation

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for the great team proposal, appreciate it!

**Comment by huan** [comment]
Please turn off the "content made for kids" for your YouTube video, or I can not add your great video to our Wechaty play list.

Learn more from https://support.google.com/youtube/answer/9632097?nohelpkit=1&hl=en

Thanks!

**Comment by sajen-k** [comment]
> Please turn off the "content made for kids" for your YouTube video, or I can not add your great video to our Wechaty play list.
> 
> Learn more from https://support.google.com/youtube/answer/9632097?nohelpkit=1&hl=en
> 
> Thanks!

@huan now the "content made for kids" is turned off. Thank you!

**Pull request merged**
