### PR TITLE
Added Styling Sheets for the New Landing Page

### PR DESCRIPTION
**Pull request by arnabiscreating**
Issue Number : #912 
This is the new landing page's styling sheet (CSS file). 
It contains all of the website's section styling. 

Note: If we merge this PR first, we'll be able to commit more sections to the landing page and the CI will work properly for future PRs.

### CODE REVIEW

**Comment by Rohitesh-Kumar-Jain** [comment]
What about you opening a draft PR for the landing page, containing all the the work that you have done so far, ignoring the CI (we can later close that draft/rough PR). Because it's hard to review 3000+ lines of CSS, and we don't wish to merge redundant code (if any) in the master branch.

Instead, we can also create a separate branch for a landing page in the original wechaty repo, and can merge this there and will merge the landing page branch in the original wechaty repo once the landing page is ready and reviewed.

@lijiarui what do you think

**Comment by lijiarui** [comment]
> What about you opening a draft PR for the landing page, containing all the the work that you have done so far, ignoring the CI (we can later close that draft/rough PR). Because it's hard to review 3000+ lines of CSS, and we don't wish to merge redundant code (if any) in the master branch.
> 
> Instead, we can also create a separate branch for a landing page in the original wechaty repo, and can merge this there and will merge the landing page branch in the original wechaty repo once the landing page is ready and reviewed.
> 
> @lijiarui what do you think

Thanks @Rohitesh-Kumar-Jain  I strongly agree with you, as @huan mentioned before, every PR should be atomic.  See: https://github.com/wechaty/wechaty.js.org/issues/912#issuecomment-864216008  #jcai 

@encodeArnab Please follow @huan suggestion in https://github.com/wechaty/wechaty.js.org/issues/912#issuecomment-864216008

**Comment by arnabiscreating** [comment]
> What about you opening a draft PR for the landing page, containing all the the work that you have done so far, ignoring the CI (we can later close that draft/rough PR). Because it's hard to review 3000+ lines of CSS, and we don't wish to merge redundant code (if any) in the master branch.

Okay, for the CSS file, we'll generate a drafted atomic PR. Actually, we wanted to integrate this file first because then the CI will not throw an error.

> Instead, we can also create a separate branch for a landing page in the original wechaty repo, and can merge this there and will merge the landing page branch in the original wechaty repo once the landing page is ready and reviewed.

Okay that will be great.
So I am closing this PR.

**Comment by sajen-k** [comment]
> What about you opening a draft PR for the landing page, containing all the the work that you have done so far, ignoring the CI (we can later close that draft/rough PR). Because it's hard to review 3000+ lines of CSS, and we don't wish to merge redundant code (if any) in the master branch.

@Rohitesh-Kumar-Jain Like do you mean to create a new PR which contains all the works that we have done till now?

we have completed the integration of the new landing page with the docusaurus and tested locally in wechaty.js.org repo and everything is working well without any issues.

**Comment by Rohitesh-Kumar-Jain** [comment]
> @Rohitesh-Kumar-Jain Like do you mean to create a new PR which contains all the works that we have done till now?

@sajenjeshan1222  Please follow @huan suggestion in #912

**Comment by sajen-k** [comment]
@Rohitesh-Kumar-Jain ok

**Pull request closed without merging**
