### PR TITLE
added a blog

### PR DESCRIPTION
**Pull request by Jesn**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [ ] Add `<!--more-->` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

### CODE REVIEW

**Comment by huan** [comment]
Cloud you please fix the problems which failed the CI, and add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username?

And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

**Comment by huan** [comment]
Kindly ping @Jesn

**Comment by lijiarui** [comment]
ping @Jesn

**Comment by lijiarui** [comment]
ping @Jesn

**Comment by lijiarui** [comment]
ping @Jesn 

If you couldn't fix this pr, I will close this at the end of May.

Thanks!

**Comment by lijiarui** [comment]
Close this pull request for a long time no reply.

**Pull request closed without merging**
