### PR TITLE
add blog 2020-05-05-when-bus-come.md

### PR DESCRIPTION
**Pull request by ershing**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `<!--more-->` section to just show the abstract in blog homepage.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/Chatie/blog#contribute-guideline)

### CODE REVIEW

**Comment by ershing** [comment]
add blog 2020-05-05-when-bus-come.md

**Comment by lijiarui** [comment]
Thanks for your blog!

Please: 
- [ ] Add teaser image for the blog
- [ ] Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

Then I can merge this PR.

**Comment by ershing** [comment]
> Thanks for your blog!
> 
> Please:
> 
> * [x]  Add teaser image for the blog
> * [x]  Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
> 
> Then I can merge this PR.

i have done that two steps, please merge this pr

**Comment by lijiarui** [comment]
Please notice: 

Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

This means: you should add your author data at `authors.yml` instead of in your blog file.

So actually you just finish the first step and haven't finished the second step yet.

**Comment by ershing** [comment]
> Please notice:
> 
> Add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!
> 
> This means: you should add your author data at `authors.yml` instead of in your blog file.
> 
> So actually you just finish the first step and haven't finished the second step yet.

actually, i fail adding my author data at authors.yml: https://github.com/Chatie/blog/pull/2/commits

**Comment by lijiarui** [comment]
I'm sorry I forgot to update the new url, you should update the author yml here: 

https://github.com/wechaty/wechaty.github.io/blob/master/_data/authors.yml

Thanks!

**Comment by huan** [comment]
@ershing It seems that you have deleted your fork for this repository?

A PR needs to read the source from your forked repository, so could you please fix it, so that we can continue working on it?

**Comment by ershing** [comment]
> @ershing It seems that you have deleted your fork for this repository?
> 
> A PR needs to read the source from your forked repository, so could you please fix it, so that we can continue working on it?

i'm sorry , i've opened another pr:[#241](https://github.com/wechaty/wechaty.github.io/pull/241), please merge that one.

**Comment by huan** [comment]
Thanks for the reply! Then let's close this issue for now and looking forward to your new PR!

**Pull request closed without merging**
