### PR TITLE
Added link colour according to the theme

### LINKED ISSUE #1364: Wechaty.js.org Link cannot displayed as expect.
We can not identify which is the link and which is not, for example:

image

I think the landing page team may change some CSS style by mistake. @Rohitesh-Kumar-Jain Could you help the landing page team to fix this problem? Thanks!

### PR DESCRIPTION
**Pull request by arnabiscreating**
Closes #1364

### CODE REVIEW

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Let's approve this quickly so that we can achieve more iterations if needed.

**Review by iamrajiv — APPROVED** [review]

**Comment by huan** [comment]
From my understanding: a React component should use Shadow DOM to encapsulate all CSS, which means the CSS in a React component should not affect the HTML page outside of this component?

1. If so, why has this CSS change affected all our websites?
1. If not, could we fix the React component CSS to only affect itself?

**Comment by arnabiscreating** [comment]
Hello @huan, 
> 1. If so, why has this CSS change affected all our websites?

Some tags, such as anchor tags, are globally scoped since they are used to give links in the Navbar and Footer, therefore any changes to these tags anywhere would effect the entire website.

> 2. If not, could we fix the React component CSS to only affect itself?

The best approach I can think of to keep these attributes within the component is to use unique id names or a selector that is not globally scoped.

**Comment by huan** [comment]
> therefore any changes to these tags anywhere would affect the entire website.

@encodeArnab Could you please double confirm it?

According to the [Google Web Fundamentals: Shadow DOM](https://developers.google.com/web/fundamentals/web-components/shadowdom), it said that:

> Shadow DOM fixes CSS and DOM. It introduces scoped styles to the web platform. Without tools or naming conventions, you can bundle CSS with markup, hide implementation details, and author self-contained components in vanilla JavaScript.

I believe the **scoped styles** and **self-contained components** are what we need, and it seems that can solve our CSS pollution problem?

### See also

- https://css-tricks.com/encapsulating-style-and-structure-with-shadow-dom/
- https://vaadin.com/learn/tutorials/css-encapsulation-with-shadow-dom

**Review by shraddhavp — APPROVED** [review]
LGTM

**Pull request merged**
