### PR TITLE
Hkenter/blog

### PR DESCRIPTION
**Pull request by hkenter**
blog finished

### CODE REVIEW

**Comment by huan** [comment]
Cloud you please fix the problems which failed the CI, and add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username?

And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

**Comment by hkenter** [comment]
> Cloud you please fix the problems which failed the CI, and add your self as an author to the author data file at https://github.com/Chatie/blog/blob/master/docs/_data/authors.yml with your GitHub username?
> 
> And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

It seems to be OK. If you have any questions, please feel free to reply to me. Thank you！

**Review by huan — APPROVED** [review]
LGTM

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
I have invited you to join the GitHub Wechaty Contributor team, welcome to join us!

> You've invited Kelly Cheng to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

And we also have a Wechaty Contributor WeChat group, please contact @lijiarui if you would like to join.

**Comment by lijiarui** [comment]
@hkenter Could you add my wechat: ruirui_0914 And I would like to invite you to wechaty contributor group.

Thanks!

**Pull request merged**
