### PR TITLE
Add blog 2020-08-04-wechaty-guangzhou-gathering.

### PR DESCRIPTION
**Pull request by fish-ball**
ake sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [x] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

### CODE REVIEW

**Comment by lijiarui** [comment]
Thanks for your good blog!

Please make GitHub action green and then I can review your blog.

**Comment by lijiarui** [comment]
ping @fish-ball

**Comment by lijiarui** [comment]
ping @fish-ball

**Comment by wj-Mcat** [comment]
ping @fish-ball . Please make CI green, so we can merge this pr.

**Comment by huan** [comment]
Thank you very much for sharing this great post, the blog is online with URL <https://wechaty.js.org/2020/08/04/wechaty-guangzhou-gathering>

**Pull request merged**
