### PR TITLE
Added running locally instructions on the main readme file

### PR DESCRIPTION
**Pull request by vasvi-sood**

### CODE REVIEW

**Comment by proudofsimin** [comment]
Is it the reopen for #876?

**Comment by vasvi-sood** [comment]
> Is it the reopen for #876?

Yes

**Review by proudofsimin — APPROVED** [review]
This is the reopen and no change for document content.

**Comment by vasvi-sood** [comment]
> This is the reopen and no change for document content.

We will close that PR, as the master branch for that PR was ahead of wechaty master.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Comment by Rohitesh-Kumar-Jain** [comment]
@abhishek-iiit I would be glad if you may have a look at this PR, before we proceed further towards merging : )

**Review by abhishek-iiit — APPROVED** [review]
Sorry for the delay ;-;  the linked PR LGTM :)

**Comment by iamrajiv** [comment]
@Rohitesh-Kumar-Jain Closing the PR and opening again might work.

**Comment by huan** [comment]
It's strange that this PR has received 3 approvals but still shows:

> Merging is blocked
> Merging can be performed automatically with 3 approving reviews.

It might a GitHub bug... Please try other PRs and see if others have this problem?

**Comment by Rohitesh-Kumar-Jain** [comment]
> It's strange that this PR has received 3 approvals but still shows:
> 
> > Merging is blocked
> > Merging can be performed automatically with 3 approving reviews.
> 
> It might a GitHub bug... Please try other PRs and see if others have this problem?

Unable to merge this one as well #1100

**Review by lijiarui — APPROVED** [review]
LGTM

**Pull request merged**
