### PR TITLE
Add Post Matrix-Wechat-Bridge

### LINKED ISSUE #194: Invite @cubesky to share his experience for setting up the `matrix-appservice-wechaty` for [Matrix]
See: https://github.com/wechaty/matrix-appservice-wechaty/issues/25#issuecomment-591762056

CC: @ericmigi

### PR DESCRIPTION
**Pull request by cubesky**
Fixes #194 .

Make sure these boxes are checked before creating your pull request -- thank you!

- [x] Add Blog Header, including title, author, date.
e.g.
```
---
 
 title: "'Score Your Face Photo' a ML&Wechaty practice"
 date: 2017-09-18 09:00 +0800
 author: huyingxi
 ---
 
 > Author: [@huyingxi](https://github.com/huyingxi/wechaty_selfie) enjoying ML&Wechaty at BUPT
```
- [x] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [x] Embed the photo & video before publishing, save all external file to the blog `/download/2018` directory.
- [x] Add `<!--more-->` section to just show the abstract in blog homepage.

[See more](https://github.com/Chatie/blog#contribute-guideline)

### CODE REVIEW

**Review by huan — APPROVED** [review]
Thanks for sharing the great blog post!

**Comment by huan** [comment]
@cubesky Cloud you please sign the CLA by clicking the `[CLA | not signed yet]` on the above CLA bot reply comment before we can merge this PR?

Thanks!

**Comment by cubesky** [comment]
@huan Ok, I signed CLA

**Comment by lijiarui** [comment]
@cubesky  Could you add my wechat: ruirui_0914 And I would like to invite you to wechaty contributor group.

Thanks!

**Pull request merged**
