### PR TITLE
把youtube的视频换成了腾讯视频

### PR DESCRIPTION
**Pull request by socialok**
把youtube的视频换成了腾讯视频

### CODE REVIEW

**Review by lijiarui — CHANGES_REQUESTED** [review]
We should keep YouTube link in the blog, but add Tencent link in the blog.  For OSPP admin official account posting this big, they can choose the Tencent link version.

**Comment by socialok** [comment]
> 

所以我们是在原本博客youtube视频链接的下面直接放一个腾讯的视频链接？
还是说再发一个只含腾讯视频链接版本的博客呢～

**Comment by socialok** [comment]
> We should keep YouTube link in the blog, but add Tencent link in the blog. For OSPP admin official account posting this big, they can choose the Tencent link version.

所以我们是在原本博客youtube视频链接的下面直接放一个腾讯的视频链接？
还是说再发一个只含腾讯视频链接版本的博客

**Comment by lijiarui** [comment]
> 所以我们是在原本博客youtube视频链接的下面直接放一个腾讯的视频链接？
> 
Yes, and tell OSPP official person that they can use Tencent link in this blog.

**Comment by socialok** [comment]
> 

OK

**Comment by socialok** [comment]
> > 所以我们是在原本博客youtube视频链接的下面直接放一个腾讯的视频链接？
> 
> Yes, and tell OSPP official person that they can use Tencent link in this blog.

OK

**Pull request closed without merging**
