### PR TITLE
Fixed gitpod and google cloud shell links

### PR DESCRIPTION
**Pull request by shwetalsoni**
I have fixed the links for `gitpod` and `google-cloud-shell` pages

Screenshot from 2021-07-17 13-45-31

### CODE REVIEW

**Comment by shwetalsoni** [comment]
This fix was earlier mentioned under issue #1032

**Comment by shwetalsoni** [comment]
Tag #891

**Review by sbis04 — APPROVED** [review]

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by proudofsimin — APPROVED** [review]

**Comment by shwetalsoni** [comment]
@Rohitesh-Kumar-Jain and @proudofsimin I think this PR can be added to #1056.

**Comment by shwetalsoni** [comment]
ping @Rohitesh-Kumar-Jain and @proudofsimin

**Review by lijiarui — APPROVED** [review]
LGTM

**Pull request merged**
