### PR TITLE
added wechaty-class section

### PR DESCRIPTION
**Pull request by shraddhavp**
This PR is for Wechaty Class section 
linking #890

### CODE REVIEW

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Great work 🎉 @shraddhavp

**Review by proudofsimin — APPROVED** [review]
Thank you :)

**Comment by lijiarui** [comment]
hi @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

**Comment by Rohitesh-Kumar-Jain** [comment]
@Soumi7 We would be glad if you may once go through the PR, and either request for changes or approve the PR.

**Review by Soumi7 — APPROVED** [review]
LGTM

**Comment by Rohitesh-Kumar-Jain** [comment]
@huan I can't merge this on my own, as we don't have 3 approving reviews

**Review by huan — APPROVED** [review]
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

**Pull request merged**
