### PR TITLE
Adding Subsections in Examples

### PR DESCRIPTION
**Pull request by Soumi7**
# Examples Section Reorganization 

As proposed in issue #796 , I have created a structure for the Examples section in Tutorials : 
- Tutorials
  - Examples
    - Overview 
    - Basic
      - the-worlds-shortest-chatbot-code-in-6-lines
      - contact-bot
      - ding-dong-bot
    - Advanced
      - demo-in-tutorial
      - busy-bot
      - media-file-bot
      - room-bot
      - friend-bot
      - gist-bot
    - Intermdiate
      - hot-import-bot
      - ctrl-c-signal-bot
      - monster-bot
      - api-ai-bot
      - speech-to-text-bot
      - tuling123-bot
      - telegram-roger-bot
      - blessed-twins-bot

I have added the following structure in this PR. Will be adding the respective sections in the pages next.

The Examples section will look like this :

Screenshot from 2021-05-01 16-00-29

### CODE REVIEW

**Review by huan — APPROVED** [review]
LGTM

**Review by huan — CHANGES_REQUESTED** [review]
Thank you very much for adding those examples to our docs site!

Please make sure the CI is green before we can merge it.

**Comment by huan** [comment]
Please fix the conflict before we can merge this PR, thanks!

**Comment by Soumi7** [comment]
The conflict is because I have removed docusaurus/docs/tutorials/examples.md and added a separate section for examples. 

Its says only admins can resolve the merge conflict.

Or I could add the file in there and you can remove it later. Should I do that? Thanks!

**Comment by huan** [comment]
I believe you can resolve the conflict without the admin privileges as well.

I search and found the following two links:

1. https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
2. https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github

I hope the above two links help.

Please let me know if you can get it done or have any questions.

**Comment by Soumi7** [comment]
Thanks! It worked!

**Comment by huan** [comment]
Awesome, merged!

**Pull request merged**
