### PR TITLE
Updated  team proposal for How to Guide

### PR DESCRIPTION
**Pull request by abhishek-iiit**
* Updated Project Section due to the case of overlapping of the topics with the tutorials :)

### CODE REVIEW

**Comment by Rohitesh-Kumar-Jain** [comment]
@proudofsimin

**Comment by proudofsimin** [comment]
@abhishek-iiit 
Thank you for your effort. I actually suggest you could simply remove the "About bot" section. Background information is more or less within the scope of explanation. If you feel necessary to have this section, how about combine it with the overview section? I like how you are very considerate to your users, but "about bot" is probably not something your users will learn "how to" do things.

**Comment by abhishek-iiit** [comment]
@proudofsimin Thank you soo much for the feedback :)

**Comment by abhishek-iiit** [comment]
Added 
* Deploy with Heroku
* Deploy with Docker
* FAQ section

**Review by huan — CHANGES_REQUESTED** [review]
Please resolve the conflict in this PR before we can continue reviewing it.

**Comment by abhishek-iiit** [comment]
Resolved the conflicting file. 
Thanks, @huan for addressing this, will take care from next time :)

**Review by proudofsimin — APPROVED** [review]
Approve for document content.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
LGTM, @huan I believe the PR is ready to get merged.

**Comment by lijiarui** [comment]
@Rohitesh-Kumar-Jain  As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

**Comment by proudofsimin** [comment]
> @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in #1045
> 
> This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

@vasvi-sood Wechaty committee requested each writer in the same team to review each other's document. Could you sign it off? Thank you.

**Comment by vasvi-sood** [comment]
> > @Rohitesh-Kumar-Jain As GSoD Project PR Review Rules in #1045
> > This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.
> 
> @vasvi-sood Wechaty committee requested each writer in the same team to review each other's document. Could you sign it off? Thank you.

Ohkay sure, I'll do that

**Comment by Rohitesh-Kumar-Jain** [comment]
@vasvi-sood pls review this

**Review by huan — APPROVED** [review]
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

**Pull request merged**
