### PR TITLE
Left_sidebars_Navigation_menu

### PR DESCRIPTION
**Pull request by abhishek-iiit**
## Added Left Sidebar Navigation Menu
Screenshot from 2021-06-13 21-37-59

### CODE REVIEW

**Comment by abhishek-iiit** [comment]
I request @huan, @Rohitesh-Kumar-Jain,  @proudofsimin to please review the changes from [Added sidebars navigation](https://github.com/wechaty/wechaty.js.org/pull/939/commits/8b686485a1beb26936e8d2553140049810926bea)

**Comment by proudofsimin** [comment]
Hi, I just realize it. Do you feel it better if we align all the category names to imperative sentences? Right now most of the names start from a single tense verb, but some of them are with -ing. Or if there's any reason you do it, please let me know.
BTW, please use lower case for the *A* in *send and Accept friend requests* and the *R* in *Sending and Receiving files*.

**Comment by abhishek-iiit** [comment]
Yaa!! I feel Imperative sentences could be more impactful to the user rather than using -ing form. Thank you for the feedback, changes are made for the same.

**Review by proudofsimin — APPROVED** [review]
Thank you

**Review by Rohitesh-Kumar-Jain — CHANGES_REQUESTED** [review]
Improper PR, pls see my comments on #940, what I suggest is you to backup all of your code and documentation, before you start playing with git commands : )

**Comment by Rohitesh-Kumar-Jain** [comment]
Pls, understand we can't merge PRs like this, either refactor this one, or raise a new PR after closing this.

**Comment by abhishek-iiit** [comment]
Closing this PR and will create a new PR with clear commits, file changes, and information.

**Pull request closed without merging**
