### PR TITLE
added new blog and static assets

### PR DESCRIPTION
**Pull request by BurgerBurglar**
thank you for the heads up @huan. could you please review this when you're free?

### CODE REVIEW

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Comment by huan** [comment]
>  ✖  jekyll/assets/2021/09-the-stupidest-bot-ever-created/135114218-cd9006eb-41d3-46c6-bf4b-114988586534.jpg does not match /\.(webp|pdf|zip)$/!

Means we only accept `.webp` image format, and

>  ✖  jekyll/assets/2021/09-the-stupidest-bot-ever-created/640px-Internet_meme_about_Fuduji.svg.png does not match /\/[0-9\-a-z_]+\./!

means that we only accept all-lower-case file names with `-` instead of `_`.

**Comment by huan** [comment]
It seems that you do not understand the image file format: they can not work as you expected if you only rename them from `.xxx` to `.webp`.

**Comment by BurgerBurglar** [comment]
jpg/png 可以改名字，mp4 好像确实不能改。我转码一下，谢谢。

**Comment by BurgerBurglar** [comment]
感谢提醒，已经修改了，如果你有空，麻烦你帮我运行 CI。有一个很奇怪的事情，我已经签了 CLA，并且把邮箱地址加入我的 GitHub 帐号了，但是还是没有显示 Shuo 已经签了。

**Comment by huan** [comment]
> 我已经签了 CLA，并且把邮箱地址加入我的 GitHub 帐号了，但是还是没有显示 Shuo 已经签了。

You need to find the problem and fix it.

**Pull request closed without merging**
