### PR TITLE
Left Navigation Menu

### LINKED ISSUE #896: Update and enhance how-to-guide section
This issue is to track :
* What has been done and 
* What we are on currently working :)

## Team members
Abhishek Jaiswal - @abhishek-iiit 
Vasvi Sood  - @vasvi-sood 

# References 
- [x] **Readme(to github section)** 
- [x] **Overview** 
- [x] **Add events to the bot**
    - [x] Add events and customise a bot
- [x] **Add more functionality to your bot**
    - [x] Dealing with messages
    - [x] Manage Contacts
    - [x] Manage Rooms
    - [x] Send and Accept Friend Requests
    - [x] Sending and Receiving files
- [x] **Deploy on IM platfrom**
    - [x] Deploy in Wechat
    - [x] Deploy in Whatsapp
    - [x] Deploy in Lark
    - [x] Deploy in Gitter
    - [x] Deploy in Wechat Official Account
    - [x] Deploy in PadLocal
    - [x] Deploy in WeChat4U
- [x] **Overview with containers**
    - [x] Deploy with Heroku
    - [x] Deploy with Docker

Please link pull request to this section for the easy access.

### PR DESCRIPTION
**Pull request by abhishek-iiit**
## Redefined left-sidebar
Screenshot from 2021-07-24 16-36-14

### CODE REVIEW

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Perfect PR, very good

**Review by proudofsimin — APPROVED** [review]
Thank you.

**Comment by lijiarui** [comment]
Please resolve the conflict since some of the PR has been merged.

**Comment by lijiarui** [comment]
Hi @abhishek-iiit As GSoD Project PR Review Rules in https://github.com/wechaty/wechaty.js.org/issues/1045

This PR should follow our rules and get enough approval, then I will review this PR. So I remove the `ready to merge` tag and feel free to add this tag when it gets enough approval.

**Comment by Rohitesh-Kumar-Jain** [comment]
@vasvi-sood  We would be glad if you may once go through the PR, and either request for changes or approve the PR.

edit: sorry I tagged the wrong person 😅

**Comment by Soumi7** [comment]
I will do that for all starting 17 July.

**Review by vasvi-sood — APPROVED** [review]
This PR looks good to me.

**Review by lijiarui — CHANGES_REQUESTED** [review]
I think maybe we should change all of the `md` file to `mdx` in the doc.

And please resolve the conflict first.

**Comment by abhishek-iiit** [comment]
Closing this PR due to some extra added files into this PR. Shifted to PR #1139

**Pull request closed without merging**
