### PR TITLE
Create Developer Profile lhr0909.md

### PR DESCRIPTION
**Pull request by lhr0909**
Fixes # .

Make sure these boxes are checked before creating your pull request -- thank you!

- [ ] Add Blog Header, including title, author, date.
e.g.

``` md
---
title: "'Score Your Face Photo' a ML&Wechaty practice"
author: huyingxi
image: /assets/2020/your-blog-title/teaser.jpg
---

YOUR_FIRST_SENTENCE_SHOULD_BE_A_SUMMARY_FOR_YOUR_POST

```

- [ ] Keep all filenames & url as lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor` instead of `2017-10-06-WeChat PC Impactor`,
- [ ] Embed the photo & video before publishing, save all external file to the blog `/assets/2020` directory.
- [ ] Add teaser image for the blog
- [x] Add your self as an author to the author data file at <https://github.com/wechaty/wechaty.js.org/blob/master/_developers/YOUR_GITHUB_USERNAME.yml> with your GitHub username. And please also remember to reference yourself with the Github username in your blog post, so that we can have nice author information besides your blog after we published it!

[See more](https://github.com/wechaty/wechaty.js.org#contribute-guideline)

### CODE REVIEW

**Review by huan — CHANGES_REQUESTED** [review]
Please:

1. Save the avatar file to the assets folder so that it can be access in China.
1. Remove the N/A for your Twitter in front matter because it will case a bad link in the page.

**Comment by lijiarui** [comment]
ping @lhr0909

**Comment by lhr0909** [comment]
Closing this and favoring #504

**Comment by lijiarui** [comment]
You should close this PR if you create a new one.

**Comment by lijiarui** [comment]
Close this since it is duplicate with https://github.com/wechaty/wechaty.js.org/pull/504

@lhr0909  feel free to reopen it if this should not be closed.

**Pull request closed without merging**
