### PR TITLE
OSPP 2021: Wechaty Piggy Bro

### PR DESCRIPTION
**Pull request by ReiKohaku**
Please make sure to check the following boxes creating your pull request, thank you very much!

- [*] Add Blog Header, including title, author, image, categories, tags, etc.  
- [*] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [*] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [*] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [*] Select a beautiful and meaningful teaser image for your blog
- [*] Create your contributor profile (if you are a first time contributor)

### CODE REVIEW

**Review by lijiarui — CHANGES_REQUESTED** [review]
Good job!

Please change `2021-07-13-summer-wechaty-piggy-bro.md` to `2021-07-13-ospp-plan-your-title` as [wechaty ospp guide](https://wechaty.js.org/2021/06/24/summer-wechaty-guide/) show.

And please get your mentor review and approval.

Thanks!

**Review by lijiarui — CHANGES_REQUESTED** [review]
Good job!

Please change `2021-07-13-summer-wechaty-piggy-bro.md` to `2021-07-13-ospp-plan-your-title` as [wechaty ospp guide](https://wechaty.js.org/2021/06/24/summer-wechaty-guide/) show.

And please get your mentor review and approval.

Thanks!

**Review by lijiarui — APPROVED** [review]
LGTM！

Please get your mentor approval then I will merge this PR.

**Comment by lijiarui** [comment]
ping @ReiKohaku

**Comment by ReiKohaku** [comment]
> LGTM！
> 
> Please get your mentor approval then I will merge this PR.

My mentor don't know how to do this...

**Review by Valerieeeee — APPROVED** [review]
LGTM！

**Review by Valerieeeee — APPROVED** [review]

**Review by ninetailskim — APPROVED** [review]
LGTM！

**Comment by lijiarui** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited ReiKohaku to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add my: wechat: _ruirui_0914_ and send this pr link to me. I will invite you into Wechaty Contributor Room

Link to https://github.com/wechaty/PMC/issues/16

Cheers!

**Pull request merged**
