### PR TITLE
Update References official account

### PR DESCRIPTION
**Pull request by Soumi7**
Updates Puppet Providers - Official Account section in Puppet Providers

References issue #890

Let me know if I have to remove any parts @Rohitesh-Kumar-Jain and @proudofsimin 

Screenshots :

image

image

image

image

image

image

image

image

image

### CODE REVIEW

**Review by proudofsimin — APPROVED** [review]
Please add one sentence before the code snippet in the Usage: Run `wechaty-puppet-official-account`. Thank you

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by shraddhavp — APPROVED** [review]
LGTM

**Comment by Soumi7** [comment]
@proudofsimin have updated

**Review by huan — APPROVED** [review]
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

**Comment by shraddhavp** [comment]
@proudofsimin  please checkout the PR for approval

**Pull request merged**
