### PR TITLE
Added myself for the website

### PR DESCRIPTION
**Pull request by Ayush7614**
This PR contains

* Added myself in Contributors for the website
* Added Image of mine for the website
* Added my all introduction and all things

cc @huan @lijiarui

### CODE REVIEW

**Comment by Ayush7614** [comment]
cc @huan @ericcug

**Comment by huan** [comment]
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

1. You have signed the CLA by clicking the `[CLA | not signed yet]` button from the comments.
2. The PR has passed all the CI tests and turns _green_. (you can execute all tests locally by running `npm test`)

**Comment by Ayush7614** [comment]
image
@huan why this error is come? I can`t solve this please help me

**Comment by huan** [comment]
You can think this is a test which you must pass before you can be validated as a wechaty contributor.

A tip: use Linux 

Good luck!

**Comment by huan** [comment]
Merge this PR and fix it later.

- wechaty/wechaty.js.org#1

**Pull request merged**
