### PR TITLE
[GSoD 2021] Added Open Graph image metadata in the docusaurus site of wechaty.js.org

### LINKED ISSUE #2190: Adding Open Graph image metadata in the docusaurus site of wechaty.js.org
## 🚀 Feature

When we share https://wechaty.js.org over social media, it is good that the card they generate for the link has useful information.

#### Facebook:

Screenshot 2021-05-23 at 6 54 01 PM

#### LinkedIn:

Screenshot 2021-05-23 at 6 53 28 PM

#### Twitter:

Screenshot 2021-05-23 at 6 53 37 PM

### References:

- Use https://developers.facebook.com/tools/debug/ to validate results for Facebook.
- Use https://www.linkedin.com/post-inspector/ to validate results for LinkedIn.
- Use https://cards-dev.twitter.com/validator to validate results for Twitter.

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: wechaty/wechaty#2190
Related: #1012

### CODE REVIEW

**Review by huan — CHANGES_REQUESTED** [review]
Great to see that we can config docusaurus to have a metadata image!

Could we use the SVG file that already in our `img/` folder instead of creating a new PNG file so that we can keep using SVG files?

And please add some documentation link to docusaurus site for this config so that we can easy to track back to the config source if we need to improve it in the future.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
I think required changes have been implemented

**Review by huan — APPROVED** [review]
LGTM.

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

**Comment by iamrajiv** [comment]
@huan @Rohitesh-Kumar-Jain I don't have any team members I think this PR is good to go. @proudofsimin Can you review, please :))

**Review by shraddhavp — APPROVED** [review]
LGTM

**Pull request merged**
