### PR TITLE
Updated the Room section in API references

### PR DESCRIPTION
**Pull request by shraddhavp**
this PR updates the Room section of the Wechaty API references

### CODE REVIEW

**Comment by shraddhavp** [comment]
@huan  @proudofsimin

**Comment by shraddhavp** [comment]
@Soumi7

**Review by Soumi7 — APPROVED** [review]
Lgtm

**Comment by shraddhavp** [comment]
@Rohitesh-Kumar-Jain

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by proudofsimin — APPROVED** [review]

**Pull request merged**
