### PR TITLE
style: gitignore add .history

### PR DESCRIPTION
**Pull request by dvlin-dev**
gitignore add .history.

By the way, I think husky should be added, Add prettier and commitlint.

Because i found several code indentation problems in the warehouse and irregular submission.

Its configuration file should be configured by the official, so I didn't add it.

### CODE REVIEW

**Comment by huan** [comment]
I can not understand why we need to do this.

Please create an issue to explain it in detail to help us understand it.

Thank you very much!

**Comment by dvlin-dev** [comment]
> I can not understand why we need to do this.
> 
> Please create an issue to explain it in detail to help us understand it.
> 
> Thank you very much!

When I use vscode, it will produce .history directory to record local modification records.

like this 
image

**Comment by huan** [comment]
I have never seen this directory when I'm using vscode (in the past 6 years).

Please provide some docs for reference so that we can confirm that.

**Comment by dvlin-dev** [comment]
> I have never seen this directory when I'm using vscode (in the past 6 years).
> 
> Please provide some docs for reference so that we can confirm that.

i'm so sorry,I made a mistake. It was caused by a plugin.

Do you think it is necessary to introduce prettier and commitlint.

like this file, It has code indentation problem
https://github.com/wechaty/docusaurus/blob/2b56b0d409d062f59d6eba8ccf441615e79a67a9/docusaurus/src/theme/Footer.tsx

**Comment by huan** [comment]
I have no experience of both prettier and commitlint, so maybe not add them for now.

Thanks for trying to enhance our repo, please feel free to help us make other improvements/bug fixes to contribute to the community!

**Pull request closed without merging**
