### PR TITLE
Fixed some links in Tutorials overview page

### PR DESCRIPTION
**Pull request by shwetalsoni**

### CODE REVIEW

**Comment by shwetalsoni** [comment]
Tag #891

**Comment by shwetalsoni** [comment]
In this PR I have fixed some links in tutorials overview page as mentioned under #1032

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by proudofsimin — APPROVED** [review]

**Review by sbis04 — APPROVED** [review]

**Comment by shwetalsoni** [comment]
@Rohitesh-Kumar-Jain and @proudofsimin please add this PR to the merging list.

Thank you :)

**Review by lijiarui — APPROVED** [review]
LGTM!

**Pull request merged**
