### PR TITLE
add introduction of kai-yuan-she-2021-event

### PR DESCRIPTION
**Pull request by wj-Mcat**
We will be working with the [kai-yuan-she](https://kaiyuanshe.cn/) community and promote the each communities. This article is to introduce the [kai-yuan-she-2021-event](https://mp.weixin.qq.com/s/vxObDpoTqc810hVwr34Xhg).

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [ ] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [ ] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [ ] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [ ] Select a beautiful and meaningful teaser image for your blog
- [ ] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

### CODE REVIEW

**Review by lijiarui — DISMISSED** [review]
Where is the wechaty part?

I think the wechaty blog should have some content of wechaty.

**Comment by wj-Mcat** [comment]
> Where is the wechaty part?
> 
> I think the wechaty blog should have some content of wechaty.

This is the only forward event news for kai-yuan-she, and they will post wechaty related news in they channels, eg: wechat official account, short-video, and sub-sessions in different cities.

**Comment by lijiarui** [comment]
Well, I think it looks a little bit strange... 

Which wechaty blog will they post then?

**Comment by wj-Mcat** [comment]
There are some wechaty introduction in COSCon 2021 event which will display wechaty info in sub-sessions of each city.  Here are some conversation messages: 

```text
1. 咱们开源社的官网。会显示咱们的社区Logo, 点进去会链接到咱们的社区展示区。
2. 咱们的大会报名百格网链接，这也就是为什么希望大家在转发文案的时候加入报名网址，社区的Logo以及社区的链接展示也都会放入。
3. 开源社会有专门的文章，将曝光参与社区，里面会涉及社区的Logo以及社区的简介，到时候文章发布后，请相关社区转发。（文章发布渠道包括但不仅限于，开源社公众号，微博，简书，开源社各个社群，合作群，志愿者群，朋友圈，技术媒体的渠道等）
4. 开源社会制作曝光参与社区的视频，视频会通过我们的视频号转发到各群，朋友圈，同时会放入到开源社文章中进行传播。
```

I think we should add some wechaty introduction in this article. I will update it later.

**Comment by huan** [comment]
There are many talks from the Wechaty community that will present at the OSSCon'21.

I'd like to suggest that we should put and forecast all the Wechaty community talks in this post so that it can include all the important information.

My talk is:

> 经过组委会认真评估，恭喜您提交的演讲《Wechaty 开源社区文档协作 Google Season of Docs 实践分享》已经通过。

**Comment by wj-Mcat** [comment]
@huan how do you think about this blog content ?

**Comment by huan** [comment]
It's definitely a better one than before, thank you very much for adding more related information to our Wechaty community!

If I have not remembered wrong, @lijiarui has another talk at this event.

I'm not sure whether we have other speakers from our contributors.

**Comment by wj-Mcat** [comment]
It seems that there is no more talker from wechaty community. So, let's merge it. How do you think about? @huan

**Review by huan — APPROVED** [review]
LGTM

Thank you for sharing this great event with our Wechaty community!

**Comment by wj-Mcat** [comment]
@lijiarui please help me merge this pr.

**Review by lijiarui — APPROVED** [review]
LGTM

**Pull request merged**
