### PR TITLE
add a blog

### PR DESCRIPTION
**Pull request by iTingle**

### CODE REVIEW

**Comment by iTingle** [comment]
@huan 
hope check please,thanks

**Comment by huan** [comment]
Congratulations! It seems that your commits passed the CLA.

However, you need to fix the following linting problem in this PR so that we can merge it:

https://github.com/wechaty/wechaty.js.org/pull/621/checks?check_run_id=1548216326#step:5:24

**Comment by iTingle** [comment]
> Congratulations! It seems that your commits passed the CLA.
> 
> However, you need to fix the following linting problem in this PR so that we can merge it:
> 
> https://github.com/wechaty/wechaty.js.org/pull/621/checks?check_run_id=1548216326#step:5:24

@huan thank you for your reminder. It's  fixed now

**Comment by huan** [comment]
You can find the CI result at the bottom of this PR like the following screenshot:

image

We need to make it green before we can continue processing this PR which means it passed the check.

You can run `npm test` before you push and get the CI running on your local system.

**Review by huan — CHANGES_REQUESTED** [review]
I'd like to merge this PR after it passed the CI.

Please fix it, thank you very much.

**Comment by iTingle** [comment]
@huan I had try download the https://github.com/wechaty/wechaty.js.org  source code,run the npm test, it still error

**Comment by huan** [comment]
@iTingle  Thank you very much for your contribution!

> You've invited iTingle to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

And we also have a WeChat room for contributors only which can discuss Wechaty at a deep level, you are welcome to join and if you are interested please contact @lijiarui to ask for an invitation.

Cheers!

**Pull request merged**
