### PR TITLE
Proposal for Volunteering

### PR DESCRIPTION
**Pull request by iamrajiv**

### CODE REVIEW

**Review by huan — CHANGES_REQUESTED** [review]
Hi Rajiv, thank you very much for your proposal for volunteering!

It's great to know that you are the GSoD'20 participant who contributed to the gRPC Gateway, which our Wechaty ecosystem is also benefiting from this project!

For your volunteering proposal: could you please add more details to your proposal, so that we can get to know what you can contribute during the season of docs?

For example, we have already two volunteer proposals already, you can read their proposal first, then let us know what you can contribute more besides their contributions.

I'm looking forward to receiving your new proposal in detail, thanks!

Huan

**Comment by iamrajiv** [comment]
Hello, @huan. Thank you for the suggestion. I have updated the proposal. Please take a look.

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> You've invited Rajiv Singh to Wechaty! They'll be receiving an email shortly. They can also visit https://github.com/wechaty to accept the invitation.

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message.

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/wechaty.js.org/tree/master/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!

**Pull request merged**
