### PR TITLE
Add tutorial for Media File Bot

### PR DESCRIPTION
**Pull request by sbis04**
I have added the tutorial for the **Media File Bot** under the `Tutorials > Examples > Advanced` section. Also, I have updated the link under tutorials overview so that it points to the correct page.

The page looks like this:

Media File Bot

Tag #891

### CODE REVIEW

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Review by proudofsimin — APPROVED** [review]

**Review by shwetalsoni — APPROVED** [review]

**Comment by sbis04** [comment]
@Rohitesh-Kumar-Jain @proudofsimin I think this PR can be added to #1056

**Review by lijiarui — APPROVED** [review]
Good job!

**Comment by Rohitesh-Kumar-Jain** [comment]
@nibble0101 pls  resolve the conflict, and then ping for merge

**Comment by Rohitesh-Kumar-Jain** [comment]
@sbis04 i have merged #1138

**Comment by sbis04** [comment]
@Rohitesh-Kumar-Jain I have fixed the conflict

**Pull request merged**
