### PR TITLE
[GSoD 2021] Added Progressive Web Application (PWA) support for the Docusaurus site

### LINKED ISSUE #708: Add manifest.json to our website
To enable our site as a PWA (Progress Web Application).

Our plan is to put different `manifest.json` under `/blogs` and `/docs` so that we can have a **Blog App** and **Docs App** for Wechaty on your phone.

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #708
Related: #1012

Screenshot 2021-05-30 at 11 20 56 AM
Screenshot 2021-05-30 at 11 21 22 AM

### CODE REVIEW

**Comment by iamrajiv** [comment]
Hi, @huan. I have added PWA for the Docusaurus site. I will add PWA for the Jekyll site in the next PR so that changes get easy to review.

**Review by Rohitesh-Kumar-Jain — COMMENTED** [review]
Hi, @iamrajiv thanks for solving the #708 issues, great work.

But I am afraid this ain't related to GSoD 2021? There's probably nothing for @proudofsimin to review in this PR I guess?

It's great that you are working apart from your technical writing duties, please continue doing this if you can. But at the same time, I would like to request that you please first prioritize the deliverables that you proposed in your [proposal](https://wechaty.js.org/2021/05/18/gsod-2021-proposal-for-improve-the-grpc-and-openapi-ecosystem/), and I see you probably are lacking behind.

You are a good programmer I see, so I would like to suggest that you keep working on programming tasks in Wechaty and maybe even participate in Google Summer of Code next year from Wechaty! But please deliver your deliverables as per your current project proposal on time.

I don't see how this task is related to GSoD'21 and your project so you may remove the GSoD'21 label from it, but please add all this extra work in your final project report and as a volunteer, I will give you extra points for all the extra work you are doing for the org.

as for the review, I don't think I and even @proudofsimin are the best people for reviewing it, this should be reviewed by a senior developer I believe.

**Review by Rohitesh-Kumar-Jain — COMMENTED** [review]
You were advocating for .webp images a few days back, is it more beneficial to prefer .png images over .webp here?

**Comment by iamrajiv** [comment]
Hi, @Rohitesh-Kumar-Jain thanks for reviewing. This PR is considered in the miscellaneous work that I mention in the video proposal, i.e., about improving the code when necessary to enhance docs. For Week 1 and Week 2 work, I have completed adding more details in the getting started section and adding more blogs in OpenApi docs and will create the PRs today. These are only two tasks which I have to do in [wechaty.js.org ](https://github.com/wechaty/wechaty.js.org) repository other than the rest of the work I have to do in [grpc](https://github.com/wechaty/grpc) and [openapi](https://github.com/wechaty/openapi). In WebP and PNG images, I think WebP is fine since WebP lossless images are smaller in size than PNGs.

**Comment by Rohitesh-Kumar-Jain** [comment]
Thanks for letting me know : )

> about improving the code when necessary to enhance docs

I wasn't expecting this in GSoD, that's quite a maverick way to improve docs, but it's great to have some like you in the team!

**Comment by proudofsimin** [comment]
Thanks @Rohitesh-Kumar-Jain and @iamrajiv. I guess I will skill this non-doc PR.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Just following the PR reviewal SOP

**Review by huan — APPROVED** [review]
LGTM.

This is awesome work, I can't wait for testing this PWA feature online, well done!

Please read and follow #1257, and feel free to help yourself to merge it by following the merge workflow.

Thank you very much!

**Comment by iamrajiv** [comment]
@huan @Rohitesh-Kumar-Jain I don't have any team member I think this PR is good to go. @proudofsimin Can you review, please :))

**Comment by huan** [comment]
@iamrajiv You can count me in as your team member, and I have already approved. :)

**Comment by iamrajiv** [comment]
@Rohitesh-Kumar-Jain I think this can be merged.

**Review by shraddhavp — APPROVED** [review]
LGTM

**Pull request merged**
